
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-0f5c00" class="brxe-section bricks-lazy-hidden"><div id="brxe-e017e9" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-8f1f5c" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-046b1f" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-eb2e21" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-1bc5c7" class="brxe-heading">Informations sur les opérations d'investissement</h1><div id="brxe-cb0c51" class="brxe-text"><p>Au service de votre patrimoine. Depuis 1868.</p>
</div></div></div></div><div id="brxe-b55f5a" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-cce4ca" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><h3 id="brxe-13af81" class="brxe-heading">Informations sur les opérations d'investissement</h3><div id="brxe-2353ae" class="brxe-block download-block bricks-lazy-hidden"><div id="brxe-9fa6ae" class="brxe-text-basic download-txt">Informationen über das Anlagegeschäft</div><a id="brxe-76aea2" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/Information-ueber-das-Anlagegeschaeft_d_V02_0622.pdf" target="_blank">Télécharger</a></div><div id="brxe-134626" class="brxe-block download-block bricks-lazy-hidden"><div id="brxe-2a2558" class="brxe-text-basic download-txt">Informations sur les activités de placement</div><a id="brxe-291925" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/FIDLEG_Informations-sur-les-activites-de-placement_f_V02_0622.pdf" target="_blank">Télécharger</a></div><div id="brxe-f47846" class="brxe-block download-block bricks-lazy-hidden"><div id="brxe-1d1828" class="brxe-text-basic download-txt">Nota informativa sull'attività di investimento</div><a id="brxe-c69049" class="brxe-button download-btn bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/Information-ueber-das-Anlagegeschaeft_i_V02_0622.pdf" target="_blank">Télécharger</a></div><div id="brxe-ab057e" class="brxe-block download-block bricks-lazy-hidden"><div id="brxe-d69bdb" class="brxe-text-basic download-txt">Information about the investment business</div><a id="brxe-b309e3" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/FIDLEG_Information-concerning-the-investment-business_e_V02_0622.pdf" target="_blank">Télécharger</a></div></div></section><div id="brxe-abba68" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Bulletin d'information</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Soyez le premier à découvrir les dernières nouveautés et des conseils financiers utiles. Inscrivez-vous dès maintenant à notre newsletter et ne manquez plus aucune mise à jour importante. </p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="brxe-1a6463" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="fr_FR">
			
				<div class="form-group" role="group">
				<input id="form-field-63165b" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="Adresse électronique" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">S'inscrire</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      