
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-2fa669" class="brxe-section bricks-lazy-hidden"><div id="brxe-d7fcdc" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-b37196" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-45023e" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-97d0d9" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-317141" class="brxe-heading">Finanzierung von Immobilien</h1><div id="brxe-32e73b" class="brxe-text"><p>Worauf kommt es beim Kauf einer Immobilie an?</p>
</div><a id="brxe-4f7847" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-bdae77" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-746fd7" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-3c93df" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-d35606" class="brxe-text gold-txt"><p>Die Finanzierung einer Immobilie muss im Zusammenhang mit der gesamthaften Vermögensverwaltung gesehen werden.</p>
</div><div id="brxe-5121ba" class="brxe-text"><p>Im Rahmen einer gesamtheitlichen Vermögensberatung und -betreuung bieten wir Ihnen Hypotheken und Belehnungen von Wertschriften an.</p>
</div></div><div id="brxe-43e6d6" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-bcc493" class="brxe-text"><p>Ihr Nutzen bei der Beschaffung von Immobilien:</p>
</div><div id="brxe-7fec79" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-605989" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-1309bb" class="brxe-text"><p>Finanzierung von Eigenheimen</p>
</div></div><div id="brxe-0b0b7a" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-59dcee" class="brxe-text"><p>Finanzierung von Mehrfamilienhäusern</p>
</div></div><div id="brxe-10cecc" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-5199b2" class="brxe-text"><p>Vergabe von Baukrediten</p>
</div></div></div></div><div id="brxe-2548f8" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-085e79" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-655015" class="brxe-block bricks-lazy-hidden"><div id="brxe-3068bb" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-0aee28" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-6884e2" class="brxe-text-basic team-name">Christof Keller</div><div id="brxe-d7ffa5" class="brxe-text-basic team-position">Leiter Finanzierungen</div><div id="brxe-36af0f" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-15ae12" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686152">044 268 61 52</a><a id="brxe-86be84" class="brxe-button bricks-button bricks-background-primary" href="mailto:christof.keller@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-dd164c" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-6e6a16" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-34d4df" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-3ceef4" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-a3d890" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-c33c36" data-script-id="c33c36" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c33c36-0" aria-expanded="false" id="accordion-c33c36-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie funktioniert eine Immobilienfinanzierung bei Hugocrest?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c33c36-0" id="panel-accordion-c33c36-0"><p>Auf Grundlage Ihrer Vorgaben entwickeln wir tragfähige und flexible Immobilienfinanzierungen, die perfekt auf Ihre Bedürfnisse abgestimmt sind. Unser Ansatz basiert auf einer ganzheitlichen Analyse Ihrer individuellen Anforderungen.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c33c36-1" aria-expanded="false" id="accordion-c33c36-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Arten von Immobilien finanzieren Sie?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c33c36-1" id="panel-accordion-c33c36-1"><p>Innerhalb der Schweiz mit besonderem Fokus auf den Kanton Zürich bieten wir massgeschneiderte Finanzierungen für eine Vielzahl von Immobilien an: Einfamilienhäuser, Eigentumswohnungen, Ferienobjekte, Luxusimmobilien, Baugrundstücke sowie Mehrfamilienhäuser.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c33c36-2" aria-expanded="false" id="accordion-c33c36-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Hypothekarmodelle bieten Sie an?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c33c36-2" id="panel-accordion-c33c36-2"><p>Festhypothek: Neben dem festen Zinssatz haben Festhypotheken eine feste Laufzeit von üblicherweise 2 bis 10 Jahren. Schwankungen bei der Zinsbelastung können so während der gesamten Laufzeit vermieden werden. Dieses Produkt eignet sich ideal, wenn Sicherheit und Planbarkeit im Fokus stehen.</p>
<p>SARON-Hypothek: Die SARON-Hypothek ist eine Geldmarkthypothek und orientiert sich am Referenzzinssatz Compounded SARON, welcher das allgemeine Schweizer Zinsniveau für kurzfristige Gelder reflektiert. Dieses Produkt ist sinnvoll, wenn sinkende oder gleichbleibende Zinsen erwartet werden und der Kunde über einen gewissen finanziellen Spielraum verfügt.</p>
<p>Im Gespräch analysieren wir Ihre finanziellen Verhältnisse, Ihre Risikobereitschaft und Ihr Interesse am Finanzmarkt.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c33c36-3" aria-expanded="false" id="accordion-c33c36-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Bieten Sie auch Finanzierungen für Neu- und Umbauten an?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c33c36-3" id="panel-accordion-c33c36-3"><p>Ja. Baufinanzierungen für das zukünftige Eigenheim oder das Mehrfamilienhaus als spätere Wertanlage bieten wir gerne an.</p>
</div></li></ul><div id="brxe-04f4bf" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-f28883" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-3592e3" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      