
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-6c7e41" class="brxe-section bricks-lazy-hidden"><div id="brxe-43fbec" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-b75074" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-71d1d8" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-25652e" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-3bc2c7" class="brxe-heading">Finanzierung als Element einer ganzheitlichen Vermögensberatung</h1><div id="brxe-36fc77" class="brxe-text"><p>Was haben Sie als Nächstes vor?</p>
</div><a id="brxe-a744cf" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-364467" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-29f96f" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-ef3834" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-a603ff" class="brxe-text gold-txt"><p>Verwirklichen Sie mit uns Ihren Traum vom Eigenheim oder einer Immobilie als Wertanlage. Dank unserer umfassenden Expertise im Schweizer Immobilienmarkt stehen wir Ihnen als kompetenten und zuverlässigen Partner zur Seite.</p>
</div></div><div id="brxe-cc301c" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-2f9326" class="brxe-text"><p>Ihr Nutzen im Bereich Finanzierung:</p>
</div><div id="brxe-ad19c9" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-884fc7" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-7b5b26" class="brxe-text"><p>Vermittlung von Know-how für die Finanzierung von Liegenschaften auf der Basis langjähriger Erfahrung</p>
</div></div><div id="brxe-b72b87" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-d502da" class="brxe-text"><p>Breites Angebotsspektrum für Finanzierungen</p>
</div></div><div id="brxe-547577" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-74373e" class="brxe-text"><p>Festhypotheken und SARON-Hypotheken</p>
</div></div><div id="brxe-2a3c21" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-d98e18" class="brxe-text"><p>Kompetitive Zinssätze</p>
</div></div><div id="brxe-37fee6" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-88e8ca" class="brxe-text"><p>Gewährung von Baukrediten für die Realisation von Bauprojekten</p>
</div></div></div></div><div id="brxe-650ea3" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><h3 id="brxe-327b0e" class="brxe-heading">Nachhaltige Sanierungen</h3><div id="brxe-3b9c06" class="brxe-block bricks-lazy-hidden"><div id="brxe-929423" class="brxe-text"><p>Nachhaltiges Wohnen bringt Vorteile für die Umwelt und Ihre Finanzen. Durch eine nachhaltige Sanierung können Sie Ihre Energie- und Wasserrechnung reduzieren sowie den CO2-Ausstoss minimieren. Die Sanierung trägt zum Werterhalt Ihrer Immobilie bei und steigert die Wohnqualität.</p>
</div><div id="brxe-782e4d" class="brxe-text"><p>Der Bund und die Kantone unterstützen ökologisches Bauen durch Fördermassnahmen. Es gibt verschiedene Möglichkeiten, eine Sanierung durchzuführen, z.B. die Verbesserung der Wärmedämmung der Wände, die Integration erneuerbarer Heizsysteme oder den Austausch der Fenster.</p>
</div></div></div><div id="brxe-a3d378" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-7e787f" class="brxe-text"><p>Für eine Übersicht über die aktuellen Förderprogramme, einschliesslich steuerliche Anreize, besuchen Sie bitte folgende Portale:</p>
</div><div id="brxe-wbkvjy" class="brxe-block bricks-lazy-hidden"><a id="brxe-qoxmxp" class="brxe-button bricks-button bricks-background-primary" href="https://www.energiefranken.ch/de" target="_blank">EnergieFranken</a><a id="brxe-dlopky" class="brxe-button bricks-button bricks-background-primary" href="https://www.energieschweiz.ch/" target="_blank">EnergieSchweiz</a></div><div id="brxe-ziokuv" class="brxe-text"><p>Haben Sie Fragen zum Thema nachhaltige Sanierungen? Kontaktieren Sie uns für eine unverbindliche Beratung.</p>
</div></div><div id="brxe-7cb570" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-72bb4d" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-77b574" class="brxe-block bricks-lazy-hidden"><div id="brxe-0bf9fd" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-a8a136" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-f16d1c" class="brxe-text-basic team-name">Christof Keller</div><div id="brxe-bb17bd" class="brxe-text-basic team-position">Leiter Finanzierungen</div><div id="brxe-f355d6" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-cb9ffa" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686152">044 268 61 52</a><a id="brxe-2d6035" class="brxe-button bricks-button bricks-background-primary" href="mailto:christof.keller@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-850284" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-3d4c0a" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-37d1ad" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-6522d9" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-e121c2" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-eb30fe" data-script-id="eb30fe" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-eb30fe-0" aria-expanded="false" id="accordion-eb30fe-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie funktioniert eine Immobilienfinanzierung bei Hugocrest?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-eb30fe-0" id="panel-accordion-eb30fe-0"><p>Auf Grundlage Ihrer Vorgaben entwickeln wir tragfähige und flexible Immobilienfinanzierungen, die perfekt auf Ihre Bedürfnisse abgestimmt sind. Unser Ansatz basiert auf einer ganzheitlichen Analyse Ihrer individuellen Anforderungen.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-eb30fe-1" aria-expanded="false" id="accordion-eb30fe-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Arten von Immobilien finanzieren Sie?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-eb30fe-1" id="panel-accordion-eb30fe-1"><p>Innerhalb der Schweiz mit besonderem Fokus auf den Kanton Zürich bieten wir massgeschneiderte Finanzierungen für eine Vielzahl von Immobilien an: Einfamilienhäuser, Eigentumswohnungen, Ferienobjekte, Luxusimmobilien, Baugrundstücke sowie Mehrfamilienhäusern.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-eb30fe-2" aria-expanded="false" id="accordion-eb30fe-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Hypothekarmodelle bieten Sie an?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-eb30fe-2" id="panel-accordion-eb30fe-2"><p>Festhypothek: Neben dem festen Zinssatz haben Festhypotheken eine feste Laufzeit von üblicherweise 2 bis 10 Jahren. Schwankungen bei der Zinsbelastung können so während der gesamten Laufzeit vermieden werden. Dieses Produkt eignet sich ideal, wenn Sicherheit und Planbarkeit im Fokus stehen.</p>
<p>SARON-Hypothek: Die SARON-Hypothek ist eine Geldmarkthypothek und orientiert sich am Referenzzinssatz Compounded SARON, welcher das allgemeine Schweizer Zinsniveau für kurzfristige Gelder reflektiert. Dieses Produkt ist sinnvoll, wenn sinkende oder gleichbleibende Zinsen erwartet werden und der Kunde über einen gewissen finanziellen Spielraum verfügt.</p>
<p>Im Gespräch analysieren wir Ihre finanziellen Verhältnisse, Ihre Risikobereitschaft und Ihr Interesse am Finanzmarkt.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-eb30fe-3" aria-expanded="false" id="accordion-eb30fe-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Bieten Sie auch Finanzierungen für Neu- und Umbauten an?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-eb30fe-3" id="panel-accordion-eb30fe-3"><p>Ja. Baufinanzierungen für das zukünftige Eigenheim oder das Mehrfamilienhaus als spätere Wertanlage bieten wir gerne an.</p>
</div></li></ul><div id="brxe-c99314" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-3debed" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-ac80cb" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      