
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-51e3f4" class="brxe-section bricks-lazy-hidden"><div id="brxe-e51054" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-3d4eeb" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-6191a0" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-5d766d" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-85f08b" class="brxe-heading">Banque privée</h1><div id="brxe-39f0ed" class="brxe-text"><p>Faites l’expérience d’une gestion de patrimoine sur mesure et d’un conseil personnalisé, adaptés à vos objectifs financiers individuels.</p>
</div><a id="brxe-06da04" class="brxe-button bricks-button bricks-background-primary" href="/fr/contact/">Contacter maintenant</a></div></div></div><div id="brxe-4afb72" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-cc808d" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-bb483d" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-2a2d74" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-d7e4ab" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-99d019" class="brxe-heading">La gestion de patrimoine, une affaire de confiance</h3><div id="brxe-9bcc5b" class="brxe-text"><p>Faites confiance à notre longue expérience et à notre service personnalisé pour gérer votre patrimoine avec succès et en toute sécurité.</p>
</div><a id="brxe-94919a" class="brxe-button bricks-button bricks-background-primary" href="/fr/gestion-de-patrimoine/">En savoir plus</a></div></div></div><div id="brxe-iajcie" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-lwykdy" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-nyxmnj" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-thiegm" class="brxe-heading">Le conseil en investissement comme service d'orientation</h3><div id="brxe-irykwe" class="brxe-text"><p>Profitez de nos conseils d’investissement spécialisés qui vous guideront de manière sûre et compétente à travers la complexité des marchés financiers.</p>
</div><a id="brxe-dmklmt" class="brxe-button bricks-button bricks-background-primary" href="/fr/conseil-en-investissement/">En savoir plus</a></div></div><div id="brxe-yjlrrt" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-985fb5" class="brxe-container zz-section zz-left bricks-lazy-hidden"><div id="brxe-5ccce0" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-69547c" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-7b656b" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-54fe05" class="brxe-heading">Le financement comme élément d'un conseil patrimonial global</h3><div id="brxe-59a493" class="brxe-text"><p>Des solutions de financement intégrées qui constituent un élément important d’un conseil patrimonial complet et durable.</p>
</div><a id="brxe-d13b9e" class="brxe-button bricks-button bricks-background-primary" href="/fr/financement/">En savoir plus</a></div></div></div><div id="brxe-tmvqrr" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-xnkexy" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-arxswa" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-mmmeie" class="brxe-heading">Fondations</h3><div id="brxe-xhdhrx" class="brxe-text"><p>Nous vous accompagnons en tant que partenaire de confiance pour les fondations et la philanthropie. Grâce à une expertise approfondie et un conseil personnalisé, nous vous aidons à générer un impact durable.</p>
</div><a id="brxe-bxrycs" class="brxe-button bricks-button bricks-background-primary" href="/fr/planification-financiere/">En savoir plus</a></div></div><div id="brxe-ruyhqm" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-rzlhsy" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-oydenj" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-ticitf" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-tcntsl" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-mfrdjl" class="brxe-heading">La planification financière personnelle</h3><div id="brxe-bhshun" class="brxe-text"><p>Planifiez votre avenir financier grâce à notre planification financière individuelle et sur mesure, adaptée à vos objectifs.</p>
</div><a id="brxe-wmcbki" class="brxe-button bricks-button bricks-background-primary" href="/fr/planification-financiere/">En savoir plus</a></div></div></div><div id="brxe-bcpwtp" class="brxe-container zz-section zz-left bricks-lazy-hidden"><div id="brxe-kafwyo" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-daaexg" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-jaigwq" class="brxe-heading">La banque dépositaire pour les gestionnaires de fortune indépendants</h3><div id="brxe-xwrkwe" class="brxe-text"><p>Votre partenaire fiable en tant que banque dépositaire, qui soutient les gestionnaires de fortune indépendants avec des solutions individuelles.</p>
</div><a id="brxe-rwzvdp" class="brxe-button bricks-button bricks-background-primary" href="/fr/services-de-banque-depositaire/">En savoir plus</a></div></div><div id="brxe-bfdiyv" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-2524a5" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-7e8c9e" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-fd1a2d" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-5b2e62" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-a0956d" class="brxe-heading">Négociation d'actions suisses non cotées et de fonds immobiliers</h3><div id="brxe-f2b17a" class="brxe-text"><p>Profitez de possibilités de négoce exclusives pour les actions suisses non cotées et bénéficiez de fonds immobiliers attrayants.</p>
</div><a id="brxe-49b998" class="brxe-button bricks-button bricks-background-primary" href="/fr/negociation-hors-bourse/">En savoir plus</a></div></div></div></section><div id="brxe-2adccd" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Bulletin d'information</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Soyez le premier à découvrir les dernières nouveautés et des conseils financiers utiles. Inscrivez-vous dès maintenant à notre newsletter et ne manquez plus aucune mise à jour importante. </p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="brxe-1a6463" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="fr_FR">
			
				<div class="form-group" role="group">
				<input id="form-field-29efa0" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="Adresse électronique" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">S'inscrire</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      