
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-b6040e" class="brxe-section bricks-lazy-hidden"><div id="brxe-c5016a" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-4844f6" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-74dc72" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-fe1c4e" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-fe7f7f" class="brxe-heading">Die Depotbank für Finanzintermediäre</h1><div id="brxe-f2bfdf" class="brxe-text"><p>Wie steigern Sie die Zufriedenheit Ihrer Kundinnen und Kunden?</p>
</div><a id="brxe-56d01a" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-8c3d00" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-40c5ac" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-919391" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-082f68" class="brxe-text gold-txt"><p>Eine Depotbank muss die Bedürfnisse vermögender Privatkunden kennen und in den Sparten Private Banking, Immobilien und Vorsorge die Nase vorn haben. Ich brauche einen absolut vertrauenswürdigen Partner. Das bin ich nicht nur meinen Kunden, sondern auch meinem Ruf schuldig.</p>
</div><div id="brxe-de05df" class="brxe-text"><p>Wir unterstützen Sie mit einem breit gefächerten Dienstleistungsangebot, das Ihre Position als Finanzintermediär stärkt und Ihnen einen klaren Wettbewerbsvorteil verschafft.</p>
</div></div><div id="brxe-2e81b1" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-25f7fa" class="brxe-text"><p>Ihr Nutzen als unabhängiger Finanzintermediär:</p>
</div><div id="brxe-263798" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-adcdb9" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-fb9662" class="brxe-text"><p>Alle wichtigen Dienstleistungen für Private Banking, Immobilien- Management und Vorsorge aus einer Hand</p>
</div></div><div id="brxe-423cc2" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-05aa3a" class="brxe-text"><p>Sicherheit dank hoher Kapitalisierung unserer Bank</p>
</div></div><div id="brxe-4fc644" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-42a838" class="brxe-text"><p>Zugang zum Handel mit nichtkotierten Schweizer Aktien</p>
</div></div><div id="brxe-4c7875" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-93b979" class="brxe-text"><p>Professionelle Bewirtschaftung und Vermarktung der Liegenschaften Ihrer Kunden</p>
</div></div><div id="brxe-cbcc60" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-c9cb84" class="brxe-text"><p>Innovative Anlagelösungen für Freizügigkeitsguthaben und die Säule 3a</p>
</div></div></div></div><div id="brxe-3de59c" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-563bf5" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-568144" class="brxe-block bricks-lazy-hidden"><div id="brxe-824681" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-554b7c" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-b15879" class="brxe-text-basic team-name">Dominik Häubi </div><div id="brxe-845428" class="brxe-text-basic team-position">Ansprechpartner <br>unabhängige Vermögensverwalter</div><div id="brxe-1e0061" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-59238a" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686126">044 268 61 26</a><a id="brxe-c573a5" class="brxe-button bricks-button bricks-background-primary" href="mailto:dominik.haeubi@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-faeb63" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-6bfdf1" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-c1a682" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-e84463" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-fdb222" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-df70d5" data-script-id="df70d5" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-df70d5-0" aria-expanded="false" id="accordion-df70d5-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was sind die Vorteile einer Zusammenarbeit mit Hugocrest ?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-df70d5-0" id="panel-accordion-df70d5-0"><p>Sie werden durch ein eingespieltes und erfahrenes Team betreut und profitieren von kurzen Entscheidungswegen.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-df70d5-1" aria-expanded="false" id="accordion-df70d5-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie hoch müssen die verwalteten Vermögen für eine Zusammenarbeit sein?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-df70d5-1" id="panel-accordion-df70d5-1"><p>Wir verlangen kein Mindestvolumen. Wir wollen vielmehr mit Überzeugung gemeinsam wachsen.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-df70d5-2" aria-expanded="false" id="accordion-df70d5-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Existiert für die Zusammenarbeit eine digitale Schnittstelle?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-df70d5-2" id="panel-accordion-df70d5-2"><p>Ja, die Bank verfügt über die Möglichkeit, dem externen Vermögensverwalter, die Daten vollautomatisch in sein PMS zu übertragen.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-df70d5-3" aria-expanded="false" id="accordion-df70d5-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Mit welchen Dienstleistungen unterscheidet sich Hugocrest von anderen Depotbanken?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-df70d5-3" id="panel-accordion-df70d5-3"><p>Neben Finanzierungslösungen verfügt die Bank über eine eigene Liegenschaftenbewirtschaftung und -Vermarktung. Zudem profitieren die Kunden vom direkten Zugang zu unseren Spezialisten für den Handel von nicht börsenkotierten Aktien und Immofonds sowie dessen Know-how.</p>
</div></li></ul><div id="brxe-75ee9c" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-4f866a" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-d36919" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      