
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-e72145" class="brxe-section bricks-lazy-hidden"><div id="brxe-c7979d" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-b03576" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-ca0aba" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-51d730" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-ac77a9" class="brxe-heading">Immobilier</h1><div id="brxe-2c431f" class="brxe-text"><p>Profitez de notre vaste expertise dans la gestion, le courtage et l’exploitation de vos biens immobiliers.</p>
</div><a id="brxe-40a49f" class="brxe-button bricks-button bricks-background-primary" href="/fr/contact/">Contacter maintenant</a></div></div></div><div id="brxe-f9bf97" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-ec4031" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-55bd44" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-5c9587" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-0939e7" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-01a7e4" class="brxe-heading">Nos objets d'achat actuels</h3><div id="brxe-0d7494" class="brxe-text"><p>Découvrez nos propriétés sélectionnées avec soin, proposées à la vente et correspondant à vos besoins.</p>
</div><a id="brxe-97312a" class="brxe-button bricks-button bricks-background-primary" href="/fr/objets-a-acheter/">En savoir plus</a></div></div></div><div id="brxe-34b1df" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-31c3c1" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-8fd143" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-65baa7" class="brxe-heading">Nos locations actuelles</h3><div id="brxe-fb027f" class="brxe-text"><p>Trouvez des locations attrayantes et de qualité dans notre sélection actuelle et profitez d’un confort de première classe.</p>
</div><a id="brxe-a400c0" class="brxe-button bricks-button bricks-background-primary" href="/fr/locations/">En savoir plus</a></div></div><div id="brxe-e16408" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-d301fb" class="brxe-container zz-section zz-left bricks-lazy-hidden"><div id="brxe-f97fff" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-fd2262" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-7ec866" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-3571be" class="brxe-heading">Hypothèques</h3><div id="brxe-b0f55a" class="brxe-text"><p>Obtenez des solutions hypothécaires sur mesure, parfaitement adaptées à vos besoins individuels et à vos objectifs financiers.</p>
</div><a id="brxe-33a75f" class="brxe-button bricks-button bricks-background-primary" href="/fr/hypotheques/">En savoir plus</a></div></div></div><div id="brxe-1c48c4" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-ef08a3" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-49bca9" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-4b5b23" class="brxe-heading">Gestion</h3><div id="brxe-b4b366" class="brxe-text"><p>Gestion professionnelle de vos biens immobiliers résidentiels et commerciaux par nos experts expérimentés et compétents.</p>
</div><a id="brxe-e3e27b" class="brxe-button bricks-button bricks-background-primary" href="/fr/gestion-des-biens-immobiliers/">En savoir plus</a></div></div><div id="brxe-5623a3" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-a1980f" class="brxe-container zz-section zz-left bricks-lazy-hidden"><div id="brxe-a1acb0" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-876915" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-305575" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-d2dfb3" class="brxe-heading">Commercialisation</h3><div id="brxe-3237fa" class="brxe-text"><p>En confiant la commercialisation de votre bien immobilier à nos experts expérimentés et parfaitement formés, vous obtiendrez le meilleur résultat possible.</p>
</div><a id="brxe-905205" class="brxe-button bricks-button bricks-background-primary" href="/fr/commercialisation-de-biens-immobiliers/">En savoir plus</a></div></div></div></section><div id="brxe-093dee" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Bulletin d'information</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Soyez le premier à découvrir les dernières nouveautés et des conseils financiers utiles. Inscrivez-vous dès maintenant à notre newsletter et ne manquez plus aucune mise à jour importante. </p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="brxe-1a6463" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="fr_FR">
			
				<div class="form-group" role="group">
				<input id="form-field-60936b" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="Adresse électronique" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">S'inscrire</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      