
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-e72145" class="brxe-section bricks-lazy-hidden"><div id="brxe-c7979d" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-b03576" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-ca0aba" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-51d730" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-ac77a9" class="brxe-heading">Immobilien</h1><div id="brxe-2c431f" class="brxe-text"><p>Profitieren Sie von unserer umfassenden Expertise in der Verwaltung, Vermittlung und Bewirtschaftung Ihrer Immobilienobjekte.</p>
</div><a id="brxe-40a49f" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-f9bf97" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-ec4031" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-55bd44" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-5c9587" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-0939e7" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-01a7e4" class="brxe-heading">Unsere aktuellen Kaufobjekte</h3><div id="brxe-0d7494" class="brxe-text"><p>Entdecken Sie unsere sorgfältig ausgewählten Immobilien, die zum Kauf angeboten werden und Ihren Bedürfnissen entsprechen.</p>
</div><a id="brxe-97312a" class="brxe-button bricks-button bricks-background-primary" href="/kaufobjekte/">Mehr erfahren</a></div></div></div><div id="brxe-34b1df" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-31c3c1" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-8fd143" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-65baa7" class="brxe-heading">Unsere aktuellen Mietobjekte</h3><div id="brxe-fb027f" class="brxe-text"><p>Finden Sie attraktive und hochwertige Mietobjekte in unserer aktuellen Auswahl und geniessen Sie erstklassigen Wohnkomfort.</p>
</div><a id="brxe-a400c0" class="brxe-button bricks-button bricks-background-primary" href="/mietobjekte/">Mehr erfahren</a></div></div><div id="brxe-e16408" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-d301fb" class="brxe-container zz-section zz-left bricks-lazy-hidden"><div id="brxe-f97fff" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-fd2262" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-7ec866" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-3571be" class="brxe-heading">Hypotheken</h3><div id="brxe-b0f55a" class="brxe-text"><p>Erhalten Sie massgeschneiderte Hypothekenlösungen, die perfekt auf Ihre individuellen Bedürfnisse und finanziellen Ziele abgestimmt sind.</p>
</div><a id="brxe-33a75f" class="brxe-button bricks-button bricks-background-primary" href="/hypotheken/">Mehr erfahren</a></div></div></div><div id="brxe-1c48c4" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-ef08a3" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-49bca9" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-4b5b23" class="brxe-heading">Bewirtschaftung</h3><div id="brxe-b4b366" class="brxe-text"><p>Professionelle Bewirtschaftung Ihrer Wohn- und Geschäftsliegenschaften durch unsere erfahrenen und kompetenten Experten.</p>
</div><a id="brxe-e3e27b" class="brxe-button bricks-button bricks-background-primary" href="/immobilienbewirtschaftung/">Mehr erfahren</a></div></div><div id="brxe-5623a3" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-a1980f" class="brxe-container zz-section zz-left bricks-lazy-hidden"><div id="brxe-a1acb0" class="brxe-block img-col bricks-lazy-hidden"></div><div id="brxe-876915" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-305575" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-d2dfb3" class="brxe-heading">Vermarktung</h3><div id="brxe-3237fa" class="brxe-text"><p>Mit einer individuellen Vermarktung Ihrer Immobilie durch unsere erfahrenen und bestens ausgebildeten Experten erreichen Sie das beste Ergebnis.</p>
</div><a id="brxe-905205" class="brxe-button bricks-button bricks-background-primary" href="/immobilienvermarktung/">Mehr erfahren</a></div></div></div></section><div id="brxe-093dee" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-353a3c" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      