
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-5a5e67" class="brxe-section bricks-lazy-hidden"><div id="brxe-449302" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-a1141a" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-69c941" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-77851d" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-871347" class="brxe-heading">Vorsorgeplattform für Finanzintermediäre</h1><div id="brxe-7e8aae" class="brxe-text"><p>Bieten Sie Ihren Kunden erstklassige Anlage- und Vorsorgelösungen durch unsere innovative Plattform für Finanzintermediäre.</p>
</div><a id="brxe-e57558" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-aa27ad" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-376a8f" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-b0b9fb" class="brxe-block side-padding img-col bricks-lazy-hidden"></div><div id="brxe-194719" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-681b65" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-b31bac" class="brxe-heading">Banking as a Service</h3><div id="brxe-2d521c" class="brxe-text"><p>Nutzen Sie unsere Banking-as-a-Service-Angebote für umfassende und massgeschneiderte Finanzlösungen.</p>
</div><a id="brxe-8b7eb2" class="brxe-button bricks-button bricks-background-primary" href="/banking-as-a-service/">Mehr erfahren</a></div></div></div><div id="brxe-55e85d" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-ed6d6d" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-af7355" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-264608" class="brxe-heading">Vorsorge- und Anlagelösungen</h3><div id="brxe-9f473e" class="brxe-text"><p>Entdecken Sie unsere massgeschneiderten Vorsorge- und Anlagelösungen, die auf Ihre individuellen Bedürfnisse abgestimmt sind.</p>
</div><a id="brxe-f3de8a" class="brxe-button bricks-button bricks-background-primary" href="/vorsorgeberatung/">Mehr erfahren</a></div></div><div id="brxe-f02b55" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-eiiqml" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-dyhpxl" class="brxe-block side-padding img-col bricks-lazy-hidden"></div><div id="brxe-cmzixp" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-mmzafx" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-emcyav" class="brxe-heading">Depotbank-Dienstleistungen</h3><div id="brxe-dmsoip" class="brxe-text"><p>Verlassen Sie sich auf unsere professionellen Depotbank-Dienstleistungen für eine sichere und effiziente Verwaltung Ihrer Anlagen.</p>
</div><a id="brxe-ntchjk" class="brxe-button bricks-button bricks-background-primary" href="/depotbank-services/">Mehr erfahren</a></div></div></div><div id="brxe-mfywaw" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-xxtppn" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-qkmnem" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-gqtnec" class="brxe-heading">Modulare Stiftungsangebote</h3><div id="brxe-fyzocw" class="brxe-text"><p>Profitieren Sie von unseren flexiblen und modularen Stiftungsangeboten, die optimal auf Ihre Bedürfnisse zugeschnitten sind.</p>
</div><a id="brxe-dqjhaq" class="brxe-button bricks-button bricks-background-primary" href="/vorsorgeeinrichtung/">Mehr erfahren</a></div></div><div id="brxe-dzwuph" class="brxe-block img-col bricks-lazy-hidden"></div></div></section><section id="brxe-a9e0b3" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-e7b336" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-bbd39b" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-b63c69" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-0f1c16" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-c9cd9d" data-script-id="c9cd9d" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c9cd9d-0" aria-expanded="false" id="accordion-c9cd9d-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was umfasst die Vorsorgeplattform für Finanzintermediäre?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c9cd9d-0" id="panel-accordion-c9cd9d-0"><p>Unsere Plattform bietet Finanzintermediären eine ganzheitliche Lösung für:</p>
<ul>
<li>Banking-as-a-Service: Digitale Bankdienstleistungen, die nahtlos in Ihre bestehenden Systeme integriert werden können.</li>
<li>Vorsorge- und Anlagelösungen: Individualisierte Strategien für die Altersvorsorge und Anlageportfolios Ihrer Kunden.</li>
<li>Depotbank-Dienstleistungen: Effiziente Abwicklung und Verwaltung von Kundendepots.</li>
<li>Modulare Stiftungsangebote: Flexible Stiftungsmodelle, die auf die individuellen Bedürfnisse von Kunden zugeschnitten sind.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c9cd9d-1" aria-expanded="false" id="accordion-c9cd9d-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Angebote bieten wir im Stiftungsgeschäft?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c9cd9d-1" id="panel-accordion-c9cd9d-1"><p>Wir übernehmen die fachliche und operative Verwaltung von Vorsorgeeinrichtungen. Hierbei bleibt es Ihnen überlassen, ob Sie ihre eigene oder unsere bestehende Vorsorgeeinrichtung nutzen möchten. Von der Stiftungsführung bis hin zur Stiftungsbuchhaltung bieten wir ein breites Angebot an Dienstleistungen an.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c9cd9d-2" aria-expanded="false" id="accordion-c9cd9d-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was beinhalten die Depotbank-Dienstleistungen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c9cd9d-2" id="panel-accordion-c9cd9d-2"><p>Unsere Depotbank-Dienstleistungen bieten Ihnen und Ihren Kunden:</p>
<ul>
<li>Kostengünstige Konto- und Depotführung</li>
<li>Verwahrung und Verwaltung von Wertpapieren</li>
<li>Sichere Abwicklung von Transaktionen</li>
<li>Beauskunftung</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-c9cd9d-3" aria-expanded="false" id="accordion-c9cd9d-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Vorteile bietet die Plattform für Finanzintermediäre?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-c9cd9d-3" id="panel-accordion-c9cd9d-3"><ul>
<li>Effizienz: Vereinfachte Prozesse durch zentrale Verwaltung</li>
<li>Flexibilität: Modulare Lösungen, die an Ihre Anforderungen angepasst werden können.</li>
<li>Sicherheit: Einhaltung aller gesetzlichen und regulatorischen Vorgaben.</li>
<li>Innovation: Zugang zu modernsten Technologien wie API-Integrationen</li>
<li>White-Label-Lösung: Sie können Produkte und Dienste unter Ihrer eigenen Marke anbieten, während wir im Hintergrund die regulatorischen und technischen Aspekte abdecken.</li>
</ul>
</div></li></ul><div id="brxe-8cf345" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-c5c66c" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-dee4c4" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      