
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-e30956" class="brxe-section bricks-lazy-hidden"><div id="brxe-5e5ee6" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-2c4e97" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-62df83" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-322c37" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-75c6c1" class="brxe-heading">Immobilien-vermarktung</h1><div id="brxe-b71c97" class="brxe-text"><p>Professionelle und individuelle Vermarktung Ihrer Immobilien für den bestmöglichen Verkaufserfolg.</p>
</div><a id="brxe-8387d1" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-3e03f3" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-17c1b0" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-7691a0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-d62508" class="brxe-text gold-txt"><p>Die Vermarktung einer Immobilie erfordert nicht nur Marktkenntnis, sondern auch ein Gefühl für die Besonderheiten der Immobilie. Für mich ist es wichtig, dass jedes Objekt individuell präsentiert wird und die bestmöglichen Bedingungen für den Verkauf geschaffen werden.</p>
</div><div id="brxe-76d20b" class="brxe-text"><p>Im Rahmen unserer umfassenden Immobilienberatung und -betreuung bieten wir Ihnen professionelle Vermarktungsstrategien und massgeschneiderte Lösungen für den erfolgreichen Verkauf Ihrer Immobilien an.</p>
</div></div><div id="brxe-131d45" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-47c770" class="brxe-text"><p>Ihr Nutzen bei der Vermarktung von Immobilien:</p>
</div><div id="brxe-7f637d" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-f00e24" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-59b326" class="brxe-text"><p>Ihre Immobilie wird professionell und individuell präsentiert, um das Interesse potenzieller Käufer zu maximieren.</p>
</div></div><div id="brxe-214b77" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-535585" class="brxe-text"><p>Wir nutzen unsere umfassenden Marktkenntnisse, um Ihre Immobilie zu den besten Konditionen zu verkaufen.</p>
</div></div><div id="brxe-2e12b4" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-16a627" class="brxe-text"><p>Von der ersten Besichtigung bis zum Vertragsabschluss begleiten wir Sie bei jedem Schritt des Verkaufsprozesses.</p>
</div></div></div></div><div id="brxe-081110" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-578c64" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-b4854e" class="brxe-block bricks-lazy-hidden"><div id="brxe-c9994f" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-a33857" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-13f137" class="brxe-text-basic team-name">Siro Roesch</div><div id="brxe-e7f66f" class="brxe-text-basic team-position">Leiter Immobilienvermarktung</div><div id="brxe-bd2808" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-b59ea9" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686262">044 268 62 62</a><a id="brxe-7ff177" class="brxe-button bricks-button bricks-background-primary" href="mailto:siro.roesch@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-ca4db5" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-0f2b2b" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-332c22" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-f4bd33" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-9995ec" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-38f916" data-script-id="38f916" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-38f916-0" aria-expanded="false" id="accordion-38f916-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Warum sollte ich einen professionellen Makler für den Immobilienverkauf beauftragen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-38f916-0" id="panel-accordion-38f916-0"><p>Der Verkauf einer Immobilie ist Vertrauenssache und mit unterschiedlichen Risiken und nicht unerheblichen Mühen verbunden. Grundsätzlich sollte der Verkauf einer Immobilie immer von einem professionellen und seriösen Makler mit Marktkenntnissen vorgenommen werden. Ein lokal verankerter Immobilienmakler kennt den Markt und hat Beziehungen und ein Netzwerk zu Personen, die an einem Kauf tatsächlich interessiert sind.</p>
<p>Der Makler kümmert sich um den ganzheitlichen Prozess des Verkaufs und legt aufgrund seiner Erfahrung ein individuelles Konzept vor, mit welchem ein bestmöglicher Verkaufserfolg erzielt werden kann. Er wirkt als Bindeglied zwischen Käufer und Verkäufer und schafft gegenseitiges Vertrauen und Sicherheit. Neben dem fachlichen Know-how, welches einen professionellen Immobilienmakler auszeichnet, profitieren Sie als Verkäufer nicht zuletzt auch von der Zeitersparnis, indem Sie sich nicht selbst um alle Detailfragen und Abwicklungsbelangen kümmern müssen. Zusätzlich erzielen Sie mit dem Verkauf durch einen Makler den höchstmöglichen Verkaufspreis.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-38f916-1" aria-expanded="false" id="accordion-38f916-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Warum soll ich Hugocrest mit dem Verkauf meiner Liegenschaft beauftragen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-38f916-1" id="panel-accordion-38f916-1"><p>Als lokal verankerte Bank verfügen wir über langjährige Erfahrung in der Betreuung und Vermarktung von Immobilien. Da jede Immobilie einzigartig ist, sind unsere Dienstleistungen immer persönlich auf Sie zugeschnitten. So verkaufen wir Ihre Immobilie individuell, zu bestmöglichen Bedingungen und mit sehr wenig Aufwand für Sie.</p>
<p>Durch unsere Tätigkeiten in den Bereichen Private Banking, Immobilien und Vorsorge verfügen wir zudem über ein umfassendes Beziehungsnetzwerk. Dieses Netzwerk nutzen wir um Ihre Immobilie diskret, vertrauensvoll und vor allem erfolgreich zu vermarkten.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-38f916-2" aria-expanded="false" id="accordion-38f916-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was unterscheidet die Vermarktung von Hugocrest von Mitbewerbern?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-38f916-2" id="panel-accordion-38f916-2"><p>Als Mitglied der Schweizerischen Maklerkammer (SMK) bieten wir eine höchstpersönliche und massgeschneiderte Dienstleistung. Dies unterscheidet uns von «Online-Maklern» welche als Fixpreisanbieter und Preisbrecher im Markt unterwegs sind. Diese arbeiten mit standardisierten Prozessen und Modulen. Digitale Prozesse und Online-Bewertungstools sind natürlich durchaus praktische Hilfsmittel beim Immobilienverkauf. Aber sie allein können die persönliche, massgeschneiderte und kompetente Leistung eines professionellen Immobilienvermarkters niemals ersetzen – höchstens ergänzen.</p>
<p>Wir setzen auf eine persönliche, ehrliche und nachhaltige Zusammenarbeit, welche auf gegen-seitigem Vertrauen basiert. Durch unsere drei Kernbereiche (Immobilien, Private Banking und Vorsorge) bieten wir Ihnen zudem eine Beratung mit Blick aufs Ganze und heben uns hierzu von anderweitigen Mitbewerbern ab.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-38f916-3" aria-expanded="false" id="accordion-38f916-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie viel kostet mich die Vermarktung meiner Immobilie durch Hugocrest?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-38f916-3" id="panel-accordion-38f916-3"><p>Wir unterstellen uns dem Gesetz des Erfolges. Unser Erfolgshonorar umfasst alle unsere Dienstleistungen und wird dann fällig, wenn der Erfolg bzw. der Verkauf offiziell eingetreten ist. Unsere Provision beinhaltet ein Rundum-sorglos-Paket, sprich ein individuell vereinbartes Honorar ohne versteckte Zusatzkosten – unabhängig davon, wie viel Aufwand oder Abklärungen nötig sind.</p>
<p>Die Kosten eines Maklers können zudem bei der Grundstückgewinnsteuer geltend gemacht und somit in Abzug gebracht werden.</p>
</div></li></ul><div id="brxe-c0d054" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-752c5c" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-167057" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      