
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-239833" class="brxe-section bricks-lazy-hidden"><div id="brxe-2808a0" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-626aea" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-425411" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-07c95c" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-f0cf7f" class="brxe-heading">Vermögens-verwaltung als Vertrauenssache</h1><div id="brxe-c1e0c8" class="brxe-text"><p>Was ist Ihnen wichtig im Leben?</p>
</div><a id="brxe-81cc58" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-cdca1d" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-e1d75b" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-wibysh" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-evdivl" class="brxe-text gold-txt"><p>Ich will meine Ideen und Pläne verwirklichen. Mich auf das konzentrieren, was mir Freude macht und meinem Leben Sinn gibt. Warum soll ich mich selber um mein Vermögen kümmern, wenn es dafür Profis gibt, die es besser können?</p>
</div><div id="brxe-nrcnps" class="brxe-text"><p>Wir sorgen für eine ausgewogene Balance zwischen Performance und Risiko.</p>
</div></div><div id="brxe-ecqwhh" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-eykvep" class="brxe-text"><p>Ihr Nutzen im Bereich Vermögensverwaltung:</p>
</div><div id="brxe-llikfe" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-ogqdtz" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-yshkmv" class="brxe-text"><p>Direkt:<br>Wir investieren wenn immer möglich ins Original</p>
</div></div><div id="brxe-fbgveu" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-bshfwn" class="brxe-text"><p>Diversifiziert:<br>Weltweit diversifiziert aus Sicht eines Schweizer Investors</p>
</div></div><div id="brxe-fbhryj" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-cohfbt" class="brxe-text"><p>Diszipliniert:<br>Konsequentes Risikomanagement</p>
</div></div><div id="brxe-dbszwo" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-ctdswd" class="brxe-text"><p>Referenzwährung:<br>CHF</p>
</div></div><div id="brxe-azdbvr" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-ahvvpb" class="brxe-text"><p>Anlagestrategien:<br>Ausgewogen, Fokus Aktien Global, Fokus Aktien Schweiz</p>
</div></div><div id="brxe-gxabyv" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-tsnfqx" class="brxe-text"><p>Spezialmandat:<br>nach individueller Strategie</p>
</div></div></div></div><div id="brxe-votwob" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><h3 id="brxe-nzqbrb" class="brxe-heading">Transfer-Service</h3><div id="brxe-ddpfnr" class="brxe-block bricks-lazy-hidden"><div id="brxe-krsgbm" class="brxe-text"><p>Ein Wechsel der Bank oder Vermögensverwaltung erfordert sorgfältige Planung und Aufmerksamkeit. Zu beachten sind hierbei insbesondere die möglichen zusätzlichen Kosten, die durch den Transfer entstehen können, sowie die Sicherstellung einer fehlerfreien Übertragung der Vermögenswerte. Ein strukturierter und kontrollierter Prozess ist unerlässlich, um finanzielle Verluste und administrative Komplikationen zu vermeiden.</p>
</div><div id="brxe-pypvff" class="brxe-text"><p>Bei Hugocrest Hugocrest Bank AG übernehmen wir für Sie sämtliche administrativen Aufwände, die mit einem Wechsel verbunden sind. Dies umfasst optimierte Transferkosten und eine kontrollierte, vollumfängliche Übertragung Ihrer Vermögenswerte. Dadurch wird der Aufwand für Sie minimiert, und Sie können sicher sein, dass Ihr Vermögen sicher und effizient übertragen wird.</p>
</div></div><div id="brxe-ajbfov" class="brxe-block brx-grid bricks-lazy-hidden"><div id="brxe-ejxgzd" class="brxe-block bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-fcnhma" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 80 80" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1225"> <clipPath id="_clip1"> <rect x="0" y="0" width="79.762" height="79.762"></rect> </clipPath> <g clip-path="url(#_clip1)"> <ellipse id="Ellipse_87" cx="32.779" cy="32.544" rx="31.549" ry="31.315" style="fill:none;stroke:#047857;stroke-width:2px;"></ellipse> <path id="Pfad_784" d="M59.09,49.833l19.162,23.833c1.387,1.911 -2.667,5.978 -4.615,4.578l-24.013,-19.161" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <circle id="Ellipse_88" cx="32.779" cy="32.544" r="18.883" style="fill:none;stroke:#047857;stroke-width:2px;"></circle> </g> </g> </svg><div id="brxe-eccqog" class="brxe-text-basic">Kontrolle</div><div id="brxe-mgiplz" class="brxe-text"><p>Wir kontrollieren die Ausführungen und stellen eine fehlerfreie Übertragung von Konto, Hypotheken oder Wertschriften sicher.</p>
</div></div><div id="brxe-ovjrkw" class="brxe-block bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-shmfta" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 85 86" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1219"> <g id="Gruppe_1218"> <clipPath id="_clip1"> <rect x="0" y="0" width="84.914" height="85.328"></rect> </clipPath> <g clip-path="url(#_clip1)"> <rect id="Rechteck_999" x="53.496" y="50.261" width="30.126" height="33.774" style="fill:none;stroke:#047857;stroke-width:2px;"></rect> <path id="Linie_305" d="M53.494,58.906l30.126,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> </g> </g> </g> <path id="Linie_306" d="M62.495,45.139l-0,-28.44" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <g id="Gruppe_1221"> <g id="Gruppe_1220"> <clipPath id="_clip2"> <rect x="0" y="0" width="84.914" height="85.328"></rect> </clipPath> <g clip-path="url(#_clip2)"> <path id="Pfad_779" d="M46.981,1.293l-45.689,0l-0,82.742l46.987,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <path id="Pfad_780" d="M46.981,16.807l15.514,0l-15.514,-15.514l0,15.514Z" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <path id="Pfad_781" d="M26.496,31.26c-0,2.565 2.418,4.647 5.4,4.647c2.982,0 5.4,-2.081 5.4,-4.647c0,-2.566 -2.415,-4.647 -5.4,-4.647c-2.847,-0 -5.156,-1.919 -5.156,-4.287c-0,-2.368 2.309,-4.291 5.155,-4.291c2.846,-0 5.154,1.919 5.154,4.287" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <path id="Linie_307" d="M31.894,14.872l-0,3.162" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_308" d="M31.894,35.901l-0,3.162" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_309" d="M15.466,57.899l29.366,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_310" d="M15.466,47.479l20.099,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_311" d="M15.466,68.318l29.366,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Pfad_782" d="M63.252,65.88l9.327,0l-5.381,12.429" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> </g> </g> </g> </svg><div id="brxe-lqzdqi" class="brxe-text-basic">Support mit Dokumenten</div><div id="brxe-nzerlx" class="brxe-text"><p>Jegliche Dokumente werden für Sie vorbereitet: Kontoeröffnung bei Hugocrest, Kündigungsunterlagen bei Ihrer bisherigen Bank oder Vermögensverwaltung.</p>
</div></div></div></div><div id="brxe-yekbgn" class="brxe-container col-3-slider bricks-lazy-hidden"><div id="brxe-fyzili" class="brxe-block bricks-lazy-hidden"><div id="brxe-bovhzc" data-script-id="bovhzc" class="brxe-slider-nested bricks-lazy-hidden splide" data-splide="{&quot;type&quot;:&quot;loop&quot;,&quot;direction&quot;:&quot;ltr&quot;,&quot;keyboard&quot;:&quot;global&quot;,&quot;height&quot;:&quot;50vh&quot;,&quot;gap&quot;:&quot;0px&quot;,&quot;start&quot;:0,&quot;perPage&quot;:1,&quot;perMove&quot;:1,&quot;speed&quot;:400,&quot;interval&quot;:3000,&quot;autoHeight&quot;:false,&quot;autoplay&quot;:false,&quot;pauseOnHover&quot;:false,&quot;pauseOnFocus&quot;:false,&quot;arrows&quot;:true,&quot;pagination&quot;:true,&quot;mediaQuery&quot;:&quot;max&quot;,&quot;breakpoints&quot;:{&quot;1279&quot;:{&quot;arrows&quot;:true,&quot;pagination&quot;:true},&quot;1090&quot;:{&quot;height&quot;:&quot;450px&quot;},&quot;767&quot;:{&quot;height&quot;:&quot;400&quot;}}}"><div class="splide__track"><div class="splide__list"><div id="brxe-eidmjo" class="brxe-block bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-zgrjut" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 80 80" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1225"> <clipPath id="_clip1"> <rect x="0" y="0" width="79.762" height="79.762"></rect> </clipPath> <g clip-path="url(#_clip1)"> <ellipse id="Ellipse_87" cx="32.779" cy="32.544" rx="31.549" ry="31.315" style="fill:none;stroke:#047857;stroke-width:2px;"></ellipse> <path id="Pfad_784" d="M59.09,49.833l19.162,23.833c1.387,1.911 -2.667,5.978 -4.615,4.578l-24.013,-19.161" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <circle id="Ellipse_88" cx="32.779" cy="32.544" r="18.883" style="fill:none;stroke:#047857;stroke-width:2px;"></circle> </g> </g> </svg><div id="brxe-znjory" class="brxe-text-basic">Kontrolle</div><div id="brxe-jvgjha" class="brxe-text"><p>Wir kontrollieren die Ausführungen und stellen eine fehlerfreie Übertragung von Konto, Hypotheken oder Wertschriften sicher.</p>
</div></div><div id="brxe-lbvjgf" class="brxe-block bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-onbykl" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 85 86" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1219"> <g id="Gruppe_1218"> <clipPath id="_clip1"> <rect x="0" y="0" width="84.914" height="85.328"></rect> </clipPath> <g clip-path="url(#_clip1)"> <rect id="Rechteck_999" x="53.496" y="50.261" width="30.126" height="33.774" style="fill:none;stroke:#047857;stroke-width:2px;"></rect> <path id="Linie_305" d="M53.494,58.906l30.126,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> </g> </g> </g> <path id="Linie_306" d="M62.495,45.139l-0,-28.44" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <g id="Gruppe_1221"> <g id="Gruppe_1220"> <clipPath id="_clip2"> <rect x="0" y="0" width="84.914" height="85.328"></rect> </clipPath> <g clip-path="url(#_clip2)"> <path id="Pfad_779" d="M46.981,1.293l-45.689,0l-0,82.742l46.987,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <path id="Pfad_780" d="M46.981,16.807l15.514,0l-15.514,-15.514l0,15.514Z" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <path id="Pfad_781" d="M26.496,31.26c-0,2.565 2.418,4.647 5.4,4.647c2.982,0 5.4,-2.081 5.4,-4.647c0,-2.566 -2.415,-4.647 -5.4,-4.647c-2.847,-0 -5.156,-1.919 -5.156,-4.287c-0,-2.368 2.309,-4.291 5.155,-4.291c2.846,-0 5.154,1.919 5.154,4.287" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> <path id="Linie_307" d="M31.894,14.872l-0,3.162" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_308" d="M31.894,35.901l-0,3.162" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_309" d="M15.466,57.899l29.366,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_310" d="M15.466,47.479l20.099,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Linie_311" d="M15.466,68.318l29.366,0" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;stroke-linejoin:round;"></path> <path id="Pfad_782" d="M63.252,65.88l9.327,0l-5.381,12.429" style="fill:none;fill-rule:nonzero;stroke:#047857;stroke-width:2px;"></path> </g> </g> </g> </svg><div id="brxe-rlpopa" class="brxe-text-basic">Support mit Dokumenten</div><div id="brxe-rapqiw" class="brxe-text"><p>Jegliche Dokumente werden für Sie vorbereitet: Kontoeröffnung bei Hugocrest, Kündigungsunterlagen bei Ihrer bisherigen Bank oder Vermögensverwaltung.</p>
</div></div></div></div><div class="splide__arrows custom"><button class="splide__arrow splide__arrow--prev" type="button"><svg class="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1212"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <g id="Gruppe_1209"> <g id="Gruppe_1210"> <path id="Pfad_778" d="M23.5,10.456l-9.522,9.522l9.522,9.522" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </g> </g> </svg></button><button class="splide__arrow splide__arrow--next" type="button"><svg class="" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1211"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <g id="Gruppe_1209"> <g id="Gruppe_1210"> <path id="Pfad_778" d="M16.5,29.544l9.522,-9.522l-9.522,-9.522" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </g> </g> </svg></button></div></div></div></div><div id="brxe-skizde" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-ulfksn" class="brxe-text"><p>Clever investiert?&nbsp;</p>
</div><div id="brxe-uwfvmt" class="brxe-text"><p>Stellen Sie sich folgende und weitere Fragen zu Ihrem Portfolio:</p>
</div><div id="brxe-kxeilg" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-fsruzm" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-ahwnwt" class="brxe-text"><p>Ist mein Anlage-Portfolio diversifiziert?</p>
</div></div><div id="brxe-btppjj" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-kdkxlc" class="brxe-text"><p>Setze ich auf Titelselektion oder eine Strategie?</p>
</div></div><div id="brxe-laspzr" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-vzuwtr" class="brxe-text"><p>Ist mein Berater unabhängig?</p>
</div></div><div id="brxe-geqdaw" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-wlchsg" class="brxe-text"><p>Sind versteckte Kosten in meinem Portfolio?</p>
</div></div><div id="brxe-fqveyw" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-dswixt" class="brxe-text"><p>Wie viel Risiko kann ich eingehen?</p>
</div></div><div id="brxe-ejoizk" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-dzlihq" class="brxe-text"><p>Soll ich mit dem Strom schwimmen?</p>
</div></div></div></div><div id="brxe-svyigt" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-dragzn" class="brxe-text"><p>Was Sie von uns erwarten können:</p>
</div><div id="brxe-mcaoyu" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-dzjkzz" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-xxagxo" class="brxe-text"><p>Wir prüfen Ihre Daten vertraulich. Teil-Prüfungen Ihres Portfolios sind selbstverständlich möglich.</p>
</div></div><div id="brxe-entfyp" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-lvriev" class="brxe-text"><p>Sie erhalten eine individuelle Analyse Ihres Portfolios.</p>
</div></div><div id="brxe-chbasj" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-ksuggd" class="brxe-text"><p>Die Ergebnisse werden Ihnen in einem persönlichen Gespräch präsentiert.</p>
</div></div><div id="brxe-ozhebf" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-aftayr" class="brxe-text"><p>Wir sind stets für Sie da.</p>
</div></div></div></div><div id="brxe-skuciw" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-lphlmo" class="brxe-text"><p>Wir helfen Ihnen gerne anhand eines Portfolio-Checks Ihre optimalen Anlagen für die aktuelle Wirtschaftslage zu finden.</p>
</div></div><div id="brxe-syvbjo" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-bnsonp" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-yfcdmt" class="brxe-block bricks-lazy-hidden"><div id="brxe-aijvvl" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-quwqwa" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-mbjojg" class="brxe-text-basic team-name">Patrice R. Kellenberger </div><div id="brxe-qgnema" class="brxe-text-basic team-position">Senior Kundenberater</div><div id="brxe-sihfuq" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-gnipht" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686172">044 268 61 72</a><a id="brxe-mnprrt" class="brxe-button bricks-button bricks-background-primary" href="mailto:patrice.kellenberger@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-275ec0" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-fe08b3" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-022bbd" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-c4cf9f" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-00effd" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-44a439" data-script-id="44a439" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-44a439-0" aria-expanded="false" id="accordion-44a439-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Für wen ist ein Vermögensverwaltungsmandat die geeignete Lösung?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-44a439-0" id="panel-accordion-44a439-0"><p>Wenn Sie aufgrund mangelnder Zeit oder Interesse mit einem Vermögensverwaltungsmandat die Anlageentscheidungen an unsere Experten delegieren, profitieren Sie von unserer langjährigen Anlagekompetenz und investieren in eine Vermögensverwaltung ohne eigene Produkte, die weitestgehend auf kernsoliden Einzeltitel basiert.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-44a439-1" aria-expanded="false" id="accordion-44a439-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie wird in einem Vermögensverwaltungsmandat investiert und wie hoch sind die Kosten?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-44a439-1" id="panel-accordion-44a439-1"><p>Gemäss ihren individuellen Vorgaben erarbeiten wir mit Ihnen ihre persönliche Anlagestrategie und investieren entsprechend und im Rahmen unserer Anlagephilosophie.</p>
<p>Die Berechnungsgrundlage für die Gebühr für ein Vermögensverwaltungsmandat ist das Portfoliovermögen. Die Gebühr beinhaltet alle Kosten und Gebühren wie:</p>
<ul>
<li>Vermögensverwaltungsgebühr</li>
<li>Depotgebühr</li>
<li>Courtage</li>
<li>Steuerauszug</li>
<li>Kontoführungsspesen</li>
</ul>
<p>Unsere Gebühren sind transparent und konkurrenzfähig. Wir agieren frei von Interessenskonflikten und es gibt keine versteckten Kosten.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-44a439-2" aria-expanded="false" id="accordion-44a439-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie ist die Wertentwicklung in einem Vermögensverwaltungsmandat?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-44a439-2" id="panel-accordion-44a439-2"><p>Unser Anspruch ist, langfristig eine im Konkurrenzvergleich überdurchschnittliche und risikobewusste Wertentwicklung zu erzielen. Dass wir diesem Anspruch gerecht werden, zeigt die Wertentwicklung unserer Strategien über die letzten 10 bis 20 Jahre, welche wir Ihnen bei Interesse gerne aufzeigen.</p>
</div></li></ul><div id="brxe-3ae08b" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-5a141c" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-826206" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      