
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-drzvyc" class="brxe-section bricks-lazy-hidden"><div id="brxe-muvgkm" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-huhhpp" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-tafksl" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-qsxwly" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-bdbaww" class="brxe-heading">Gemeinsam wirksam: Die Bank für Stiftungen und Philanthropie</h1><div id="brxe-meyqzf" class="brxe-text"><p>Wie möchten Sie Wirkung entfalten?</p>
</div><a id="brxe-rsdksj" class="brxe-button bricks-button bricks-background-primary" href="#kontakt" data-brx-anchor="true">Jetzt kontaktieren</a></div></div></div><div id="brxe-iikejz" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="first-txt-section" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-hhsknk" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-dzjthw" class="brxe-text gold-txt"><p>Ich habe über die letzten Jahre schon mehrfach an gemeinnützige Organisationen gespendet und bestehende Projekte unterstützt. Doch irgendwann habe ich den starken Wunsch verspürt, die Zügel selbst in die Hand zu nehmen und mich gezielter zu engagieren. So entstand ein zweckgebundener Fonds eigens für mein Herzensprojekt.</p>
</div><div id="brxe-rpuyyb" class="brxe-text"><p>Wir kümmern uns um die Bewirtschaftung des zweckgebundenen Vermögens – damit Ihr Projekt auch morgen noch die volle Wirkung zeigt.</p>
</div></div><div id="brxe-yjwlra" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-fibnxh" class="brxe-text"><p>Unsere Kompetenzen für gemeinnützige Stiftungen und zweckgebundene Fonds</p>
</div><div id="brxe-rcmrvk" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-tnywml" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-gntyzk" class="brxe-text"><p>Vermögensverwaltung und Anlageberatung für Stiftungsvermögen</p>
</div></div><div id="brxe-smvfbx" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-hfmopd" class="brxe-text"><p>Immobilien-Kompetenz als Bewirtschafter, Vermittler und Entwickler</p>
</div></div><div id="brxe-ufedru" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-fbxfec" class="brxe-text"><p>Dank unserem Netzwerk finde Sie schneller passende Projekte und die richtigen Ansprechpartner.</p>
</div></div><div id="brxe-rxybit" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-kbzkrg" class="brxe-text"><p>Spenden und Rechnungen: Wir kümmern uns um den Zahlungsverkehr</p>
</div></div></div></div><div id="kontakt" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-cvpnwu" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-fgompn" class="brxe-block bricks-lazy-hidden"><div id="brxe-fpyvdu" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-ncwxzl" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-nhneov" class="brxe-text-basic team-name">Tobias Gugelmann</div><div id="brxe-tbkkhz" class="brxe-text-basic team-position">Ansprechpartner gemeinnützige Stiftungen</div><div id="brxe-dddqlz" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-oxguks" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686159">044 268 61 59</a><a id="brxe-qpcnbp" class="brxe-button bricks-button bricks-background-primary" href="mailto:tobias.gugelmann@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-lfavkg" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-gfsbyg" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-wqlnuo" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-duwsty" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-tjgdhj" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-qtrxdj" data-script-id="qtrxdj" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-qtrxdj-0" aria-expanded="false" id="accordion-qtrxdj-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie viel Vermögen wird für eine eigene gemeinnützige Stiftung benötigt?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-qtrxdj-0" id="panel-accordion-qtrxdj-0"><p>Eine eigenständige Stiftung bringt einmalige und wiederkehrende Aufwendungen mit sich. Um ein sinnvolles Verhältnis zu erzielen, ist erfahrungsgemäss ein Stiftungsvermögen von mindestens 3 Mio. Franken erforderlich. Selbst bei diesen hohen Beträgen kann jedoch ein zweckgebundener Fonds die effektivere Alternative sein.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-qtrxdj-1" aria-expanded="false" id="accordion-qtrxdj-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie kann das Vermögen einer gemeinnützigen Stiftung bewirtschaftet werden?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-qtrxdj-1" id="panel-accordion-qtrxdj-1"><p>Es gibt einige Stiftungen, die sehr konkrete Anlagerichtlinien in ihren Reglementen vorsehen. Wenn keine anderweitigen Vorgaben bestehen, einigt sich der Stiftungsrat häufig darauf, das Vermögen analog zu einer Pensionskasse zu bewirtschaften. In diesem Fall wird eine breit diversifizierte Strategie über verschiedene Anlageklassen hinweg vereinbart, die meist mit passiven Kollektivanlagen und Direktanlagen umgesetzt wird.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-qtrxdj-2" aria-expanded="false" id="accordion-qtrxdj-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Kann ich bei einem zweckgebundenen Fonds frei wählen, wofür die Mittel verwenden sollen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-qtrxdj-2" id="panel-accordion-qtrxdj-2"><p>Ganz frei sind Sie nicht − aber es gibt unzählige Möglichkeiten. Entscheidend ist, dass das Kriterium der Gemeinnützigkeit gemäss den Vorgaben der Dachstiftung erfüllt ist. Typische Tätigkeitsgebiete von zweckgebundenen Fonds sind zum Beispiel: Förderung von Sport, Jugendhilfe, Bildung, Wissenschaft und Forschung. Unterstützung von Kunst und Kultur. Förderung von Tierschutz und Naturschutz.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-qtrxdj-3" aria-expanded="false" id="accordion-qtrxdj-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was sind die steuerlichen Vorteile bei einer Spende an eine gemeinnützige Stiftung?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-qtrxdj-3" id="panel-accordion-qtrxdj-3"><p>Spenden, die an eine steuerbefreite und gemeinnützig anerkannte Organisation geleistet werden, können in der Schweiz vom steuerbaren Einkommen abgezogen werden. In den meisten Kantonen und beim Bund beträgt der maximal abzugsfähige Betrag 20 Prozent des Nettoeinkommens. </p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-qtrxdj-4" aria-expanded="false" id="accordion-qtrxdj-4" role="button" tabindex="0"><div class="accordion-title"><h5 class="title"> Kann ich mit meiner Nachlassregelung ein gemeinnütziges Projekt fördern?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-qtrxdj-4" id="panel-accordion-qtrxdj-4"><p>Sie können in Ihrem Testament oder Erbvertrag festlegen, dass ein bestimmter Teil von Ihrem Nachlass an eine gemeinnützige Organisation, Stiftung oder zweckgebundenen Fonds gehen soll. Ebenso ist es denkbar, bereits zu Lebzeiten ein entsprechendes Projekt ins Leben zu rufen und es dann später mit einem Teil vom Nachlass weiter zu begünstigen. Gerne informieren wir Sie über allfällige Pflichtteile.</p>
</div></li></ul><div id="brxe-ismtso" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-yocrck" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-a76de0" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      