
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-90109d" class="brxe-section bricks-lazy-hidden"><div id="brxe-0653af" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-9136da" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-f14b46" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-edfc3d" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-496cf6" class="brxe-heading">Déclaration de confidentialité</h1><div id="brxe-64be03" class="brxe-text"><p>La protection des données revêt une importance particulière pour Hugocrest Bank (ci-après la «&nbsp;Banque&nbsp;»).</p>
</div><a id="brxe-02c8fe" class="brxe-button bricks-button bricks-background-primary" href="/fr/contact/">Contacter maintenant</a></div></div></div><div id="brxe-51b616" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-e38a73" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-550db0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-281794" class="brxe-text gold-txt"><p>La protection des données revêt une importance particulière pour la Hugocrest Bank (ci-après «&nbsp;la Banque&nbsp;»). Par la présente déclaration de protection des données, la banque informe sur la nature, l’étendue et la finalité des données personnelles collectées, utilisées et traitées par la banque ainsi que sur les droits de la personne concernée. L’étendue du traitement des données personnelles par la banque dépend essentiellement des produits achetés par la personne concernée, du service convenu ainsi que des obligations légales et réglementaires relatives à la collecte et au traitement des données personnelles.  </p>
</div><div id="brxe-bnjbob" class="brxe-text"><p>Vous trouverez ici la déclaration de confidentialité en <a href="/wp-content/uploads/2025/02/Datenschutzerklaerung_LPZ_09_2023-V01-final_FR.pdf" target="_blank" rel="noopener">français</a>, <a href="/wp-content/uploads/2025/02/Datenschutzerklaerung_LPZ_09_2023-V01-final_IT.pdf" target="_blank" rel="noopener">italien</a> et <a href="/wp-content/uploads/2025/02/Datenschutzerklaerung_LPZ_09_2023-V01-final_EN.pdf" target="_blank" rel="noopener">anglais</a>. <br>Ce texte s’applique mutatis mutandis aux personnes de sexe féminin et à un nombre pluriel de personnes.</p>
</div></div><div id="brxe-yxntze" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><h3 id="brxe-xqxbjl" class="brxe-heading daten-heading">1. sources des données personnelles de la banque</h3><div id="brxe-hwerod" class="brxe-text"><p>Dans le cadre des relations d’affaires avec des clients ou des clients potentiels («&nbsp;clients&nbsp;») et des personnes physiques liées au client, les données traitées sont celles que la banque reçoit de la personne concernée (par ex. le client). La Banque reçoit également des données de prestataires de services (p. ex. agences de renseignements sur le crédit, bases de données), de registres publics (p. ex. registre du commerce, Feuille officielle suisse du commerce) ou d’autorités et de services officiels (p. ex. tribunaux, parquets) dont la Banque a besoin pour fournir le service ou pour des raisons légales ou réglementaires. Sont notamment considérées comme des personnes physiques ou morales liées toute personne : – le mandataire ou le signataire autorisé, – l’ayant droit économique et le détenteur du contrôle, – le bénéficiaire d’une opération de paiement donnée ou – toute autre personne physique ou morale ayant une relation avec le client qui est pertinente pour la relation d’affaires entre le client et la Banque.  </p>
</div><h3 id="brxe-wtegkg" class="brxe-heading daten-heading">2. types de données personnelles traitées par la banque</h3><div id="brxe-rfdbch" class="brxe-text"><p>Les catégories de données personnelles traitées par la banque comprennent les informations personnelles (par exemple, le nom, la date/le lieu de naissance, l’état civil, l’adresse, les centres d’intérêt, les relations familiales, les coordonnées (numéro de téléphone ou adresse e-mail), les données de transaction, la situation financière, les objectifs d’investissement, la résidence fiscale, le statut américain, les informations professionnelles, les données lors de l’utilisation du site web de la banque (par exemple, l’adresse IP, les cookies) ainsi que d’autres informations sur les procurations, les relations personnelles, les relations réglementaires, les fichiers journaux).</p>
<p>Il est possible que des données autres que celles mentionnées ci-dessus soient traitées lors de la conclusion d’un service ou d’un produit particulier. Il peut s’agir, par exemple, de : Données de commande, ordres de paiement, chiffre d’affaires, données de prélèvement automatique, données de documentation, comportement d’investissement, stratégie d’investissement, bilans et autres données commerciales, garanties acceptées.   </p>
<p>Dans la mesure où la Banque traite des données personnelles sensibles (par exemple des données biométriques, des données relatives à la santé ainsi que des informations sur des condamnations ou sanctions pénales ou administratives, l’origine ethnique, les opinions ou appartenances politiques, les convictions religieuses ou philosophiques), elle le fait dans le contexte :  </p>
<ul>
<li>avec un traitement pour lequel la personne concernée a donné son consentement explicite.  </li>
<li>avec l’établissement, l’exercice ou la défense de droits légaux.  </li>
<li>avec un traitement portant sur des données personnelles que la personne concernée a rendues publiques ou qui ont été rendues publiques.  </li>
<li>avec le respect des obligations légales ou réglementaires.</li>
</ul>
</div><h3 id="brxe-igdcpj" class="brxe-heading daten-heading">3. finalités du traitement des données</h3><div id="brxe-lphcpf" class="brxe-text"><p>La Banque ne collecte et ne traite que les données personnelles qui sont nécessaires à la réalisation d’un objectif spécifique. Les données personnelles sont notamment traitées pour les finalités suivantes :   </p>
<ul>
<li>en rapport avec les opérations avec la clientèle, c’est-à-dire pour pouvoir fournir les produits et services proposés par la banque, par exemple pour l’ouverture (éventuelle) ou la gestion d’une relation d’affaires.</li>
<li>pour pouvoir satisfaire aux obligations légales et réglementaires, par exemple la loi sur le blanchiment d’argent (LBA), les lois fiscales, les obligations de divulgation aux autorités.</li>
<li>en relation avec le marketing, c’est-à-dire pour améliorer les produits et services offerts ou proposer de nouveaux produits et services, par exemple au moyen du marketing direct, de l’envoi de newsletters, de l’exploitation du site web.</li>
<li>en relation avec l’intérêt légitime de la banque, par exemple à des fins de gestion des affaires et des risques, de garantie de la sécurité et de l’exploitation informatiques ou de sécurité des bâtiments et des installations.</li>
<li>en rapport avec la gestion des affaires, la gestion administrative et technique ainsi que la gestion des comptes/dépôts pour les fondations de libre passage et les fondations 3a.</li>
</ul>
</div><h3 id="brxe-ecijjc" class="brxe-heading daten-heading">4. respect des principes de protection des données</h3><div id="brxe-lgnkpb" class="brxe-text"><p>La Banque traite les données personnelles en tenant compte notamment de la loi fédérale sur la protection des données (LPD) et de l’ordonnance sur la protection des données (OPD). Ce faisant, la Banque vérifie, lors du traitement des données personnelles, que celles-ci sont traitées conformément à la loi ainsi qu’aux principes de bonne foi et de proportionnalité. Les données ne sont traitées que de la manière indiquée lors de leur collecte, de la manière reconnaissable pour la personne concernée ou de la manière prévue par une loi. Les données personnelles ne sont collectées par la Banque que dans un but précis et identifiable par la personne concernée. La Banque s’assure, en tenant compte de l’état de la technique et des coûts de mise en œuvre, par des mesures techniques et organisationnelles appropriées, que les données personnelles traitées :      </p>
<ul>
<li>ne sont accessibles qu’aux personnes autorisées</li>
<li>sont disponibles lorsque vous en avez besoin,</li>
<li>ne pas être modifiés de manière non autorisée et involontaire, et</li>
<li>être traitées de manière compréhensible.</li>
</ul>
<p>S’il s’avère que des données personnelles sont inexactes ou incomplètes, la Banque les rectifiera, les effacera ou les détruira, à moins qu’une loi ou des dispositions réglementaires ne l’interdisent.</p>
</div><h3 id="brxe-orhvbg" class="brxe-heading daten-heading">5. bases du traitement des données personnelles</h3><div id="brxe-micliu" class="brxe-text"><p>Si nécessaire, la Banque traite les données personnelles sur la base des motifs suivants :  </p>
<p><strong>5.1 Intérêt public ou privé prépondérant</strong> <br>La banque traite des données personnelles afin d’initier ou de conclure un contrat, de remplir les obligations découlant d’un contrat (p. ex. services de conseil/administration, gestion de compte/dépôt ou exécution d’ordres et de transactions), d’analyser le comportement du client, de prendre des mesures pour améliorer les produits et services ou de faire du marketing direct.  </p>
<p>La banque a également des intérêts privés légitimes à traiter des données personnelles :  </p>
<ul>
<li>pour garantir ou faire valoir les droits de la Banque à l’égard du client et lors de la réalisation de sûretés du client ou de tiers (si les sûretés de tiers ont été constituées pour des droits à l’encontre du client),</li>
<li>lors du recouvrement des créances de la banque sur le client,</li>
<li>lors de vérifications de solvabilité et de recherches effectuées par la banque auprès de centres d’information sur le crédit et d’autorités publiques</li>
<li>en cas de litige judiciaire opposant la banque au client,</li>
<li>lors de recherches d’ayants droit en cas d’absence de contact ou de nouvelles.  </li>
</ul>
<p><strong>5.2 Base légale</strong> <br>La Banque est tenue de traiter des données personnelles en vertu de différentes bases légales et réglementaires. Il s’agit notamment d’obligations légales telles que la loi sur la surveillance des marchés financiers, la loi sur les banques, la loi sur le blanchiment d’argent, la loi sur les services financiers, etc.   </p>
<p><strong>5.3 Consentement</strong> <br>Si un consentement est nécessaire pour le traitement des données personnelles, la Banque le recueille auprès de la personne concernée. Le consentement donné peut être révoqué à tout moment. Une telle révocation ne prend effet qu’à compter de sa réception par la banque et n’affecte pas la légalité du traitement des données personnelles jusqu’à la révocation. Il peut y avoir des raisons (p. ex. en vertu d’une loi) qui rendent nécessaire le traitement des données personnelles malgré la révocation. Une révocation peut entraîner la limitation de certains services ou la rupture de la relation d’affaires.    </p>
</div><h3 id="brxe-chmtmh" class="brxe-heading daten-heading">6. durée de conservation des données personnelles</h3><div id="brxe-xeokmk" class="brxe-text"><p>La Banque traite et conserve les données personnelles aussi longtemps que cela est nécessaire pour atteindre le but pour lequel les données personnelles ont été collectées ou pour remplir les obligations contractuelles ou légales. En règle générale, c’est 10 ans après la fourniture du service ou la fin de la relation d’affaires.   </p>
<p>Si les données personnelles ne peuvent pas être supprimées, des mesures techniques et organisationnelles sont prises pour garantir que :  </p>
<ul>
<li>des procédures techniques et organisationnelles sont mises en œuvre pour assurer l’intégrité des données, en particulier pour garantir l’authenticité et l’intégrité des données ou des documents (par exemple, signature numérique ou horodatage). En outre, il est garanti que les données ne peuvent pas être modifiées ultérieurement sans que cela puisse être constaté ; </li>
<li>le contenu des données soit compréhensible à tout moment</li>
<li>une journalisation et une documentation des accès et des connexions sont effectuées au moyen de «&nbsp;fichiers journaux&nbsp;».</li>
</ul>
</div><h3 id="brxe-rcodmw" class="brxe-heading daten-heading">7. droits découlant de la protection des données</h3><div id="brxe-ldvebh" class="brxe-text"><p>En principe, la personne concernée dispose des droits suivants, à moins qu’une obligation légale ne s’y oppose :</p>
<ul>
<li>Accès aux données personnelles,</li>
<li>Rectification des données personnelles,</li>
<li>la divulgation de données personnelles,</li>
<li>Transfert de données personnelles,</li>
<li>Interdiction d’un traitement particulier de données personnelles,</li>
<li>Limitation du traitement des données personnelles,</li>
<li>Révocation du consentement donné pour le traitement des données personnelles,</li>
<li>la suppression et l’opposition aux données personnelles collectées.</li>
<li>Si la fourniture de renseignements, l’émission ou la transmission de données entraîne des frais disproportionnés, la banque peut exiger une participation aux frais à hauteur de 300 £maximum.</li>
</ul>
</div><h3 id="brxe-ftjmyv" class="brxe-heading daten-heading">8. destinataires des données personnelles</h3><div id="brxe-oympxg" class="brxe-text"><p>Les données personnelles ne sont traitées que par les personnes qui en ont besoin pour remplir des obligations contractuelles ou légales et pour défendre nos intérêts légitimes. Si cela est nécessaire, les prestataires de services et les tiers (par exemple, les partenaires d’externalisation) ont accès aux données. Dans ce cas, le secret bancaire et les autres dispositions légales sont respectés.    </p>
<p>Les prestataires de services et les tiers en tant que destinataires de données personnelles peuvent être par exemple  </p>
<ul>
<li>les sous-traitants et autres prestataires de services (par exemple, les fournisseurs),</li>
<li>les organismes publics (par exemple les autorités), si une obligation légale ou administrative le prévoit.</li>
<li>les établissements de crédit et financiers ainsi que les institutions comparables (courtiers, dépositaires, bourses, etc.)</li>
<li>autres destinataires de données pour lesquels le client a donné son consentement</li>
</ul>
</div><h3 id="brxe-gbqmel" class="brxe-heading daten-heading">9. transfert de données à l'étranger</h3><div id="brxe-yzqgai" class="brxe-text"><p>En principe, il n’y a pas de transfert de données à l’étranger. Si des données personnelles sont transmises à l’étranger, elles le sont dans le respect des dispositions légales et lorsque cela est nécessaire à l’exécution du contrat (p. ex. pour le traitement de transactions internationales ou l’exécution d’ordres sur des places commerciales étrangères). Si des personnes chargées du traitement des commandes sont engagées à l’étranger, elles sont tenues de respecter le secret professionnel du banquier et la loi sur la protection des données.  </p>
</div><h3 id="brxe-prnill" class="brxe-heading daten-heading">10. traitement automatisé</h3><div id="brxe-swnuvm" class="brxe-text"><p>Dans certains cas, la Banque traite les données personnelles de manière automatisée. Cela peut se produire, par exemple, dans les cas suivants : </p>
<ul>
<li>dans le cadre de l’obligation légale de lutte contre le blanchiment d’argent et le financement du terrorisme, au moyen de la surveillance et de l’évaluation des opérations de paiement.</li>
</ul>
<p>La banque se réserve le droit de traiter à l’avenir les données personnelles de manière automatisée afin d’établir des profils de clients, de prédire des évolutions et d’identifier des caractéristiques et des traits personnels en rapport avec la personne concernée.</p>
</div><h3 id="brxe-rtftym" class="brxe-heading daten-heading">11. journalisation de certains traitements de données personnelles</h3><div id="brxe-ysxdax" class="brxe-text"><p>Si la banque devait traiter des données personnelles sensibles de manière automatisée et à grande échelle ou procéder à un profilage présentant un risque accru pour les personnes concernées, elle consignerait de tels traitements au sens d’une mesure technique et organisationnelle et les réglementerait en interne afin de pouvoir vérifier ultérieurement, par exemple, leur conformité à la finalité.</p>
</div><h3 id="brxe-glkyly" class="brxe-heading daten-heading">12. protection des données personnelles</h3><div id="brxe-qxyopp" class="brxe-text"><p>La protection des données personnelles est une priorité absolue pour la banque. Les données personnelles des clients sont soumises au secret bancaire. Les données personnelles sont traitées de manière strictement confidentielle et protégées contre l’accès de tiers non autorisés. Les personnes qui ne sont pas soumises à une obligation de confidentialité n’ont en principe pas accès aux données personnelles collectées. De même, la Banque s’assure que les destinataires des données personnelles respectent les dispositions applicables en matière de protection des données.    </p>
</div><h3 id="brxe-snnzug" class="brxe-heading daten-heading">13. données relatives à la présence sur Internet</h3><div id="brxe-afnart" class="brxe-text"><p><strong>13.1 Généralités</strong> <br>Les informations suivantes expliquent comment la Banque traite les données à l’occasion de sa présence sur Internet.  </p>
<p>Le site web de la Banque peut être utilisé sans enregistrement. Les données personnelles ne sont traitées par la Banque que dans la mesure où cela est nécessaire à l’exécution des services et produits proposés.   </p>
<p>Il n’y a pas de collecte automatique de données personnelles – à l’exception de l’adresse IP – pour l’obtention des services proposés. Si des données personnelles sont collectées, elles doivent être fournies par la personne concernée elle-même.   </p>
<p><strong>13.2 Cookies</strong> <br>Afin de rendre la visite du site web plus attrayante et de permettre l’utilisation de certaines fonctions, des cookies sont utilisés sur le site web. Il s’agit de petits fichiers texte qui sont déposés sur le terminal de l’utilisateur. Certains des cookies utilisés sont supprimés à la fin de la session de navigation, c’est-à-dire après la fermeture du navigateur (cookies de session). D’autres cookies restent sur le terminal et permettent au navigateur de reconnaître l’utilisateur lors de sa prochaine visite (cookies persistants). Si des cookies sont installés, ils collectent et traitent dans une mesure individuelle certaines informations sur l’utilisateur telles que les données de navigation et de localisation ainsi que les valeurs d’adresse IP. Les cookies persistants sont automatiquement supprimés après une durée prédéfinie, qui peut varier selon le cookie.       </p>
<p>Si vous souhaitez limiter ou bloquer les cookies stockés sur votre appareil, vous pouvez le faire en modifiant les paramètres de votre navigateur. Des informations à ce sujet sont disponibles dans la fonction d’aide du navigateur. Si les cookies sont désactivés, il est possible que certaines fonctionnalités du site Web de la Banque ne soient plus disponibles.    </p>
<p><strong>13.3 Utilisation de Google Analytics</strong> <br>Le site Web de la Banque utilise Google Analytics, un service d’analyse Web fourni par Google Inc (Google). Google Analytics utilise des cookies, qui sont des fichiers texte placés sur l’ordinateur de l’utilisateur, pour aider le site internet à analyser l’utilisation du site par ses utilisateurs. Les informations générées par le cookie sur l’utilisation du site web (y compris l’adresse IP) sont transmises à un serveur de Google et y sont enregistrées. Si l’anonymisation de l’IP est activée sur le site, l’adresse IP sera préalablement abrégée par Google dans les États membres de l’Union européenne (UE) ou dans d’autres États parties à l’accord sur l’Espace économique européen (EEE). Ce n’est que dans des cas exceptionnels que l’adresse IP complète est transmise à un serveur de Google aux États-Unis et y est abrégée.     </p>
<p>Google utilisera cette information dans le but d’évaluer l’utilisation du site Web de la Banque, de compiler des rapports sur l’activité du site Web pour les opérateurs de site Web et de fournir d’autres services relatifs à l’activité du site Web et à l’utilisation d’Internet. Google est susceptible de communiquer ces informations à des tiers en cas d’obligation légale ou lorsque ces tiers traitent ces données pour le compte de Google. Google ne recoupera pas votre adresse IP avec toute autre donnée détenue par Google. De plus amples informations sur les conditions d’utilisation et la protection des données sont disponibles sur le site web de Google Analytics. La banque attire l’attention sur le fait que sur ce site Internet, Google Analytics a été complété par le code «&nbsp;AnonymizeIP&nbsp;» afin de garantir une saisie anonyme des adresses IP (ce que l’on appelle le masquage IP).      </p>
<p>En utilisant le site web de la Banque, l’utilisateur accepte que les données collectées soient traitées par Google de la manière et aux fins décrites ci-dessus.  </p>
<p><strong>13.4 Utilisation de Google Maps</strong> <br>Le site web de la Banque utilise Google Maps, un service web de Google Inc. (Google) pour afficher des cartes (géographiques) interactives afin de représenter visuellement des informations géographiques. L’utilisation de ce service permet d’afficher la localisation de la Banque et un itinéraire. Chaque fois que le composant Google Maps est appelé, un cookie est installé par Google pour traiter les préférences et les données de l’utilisateur lors de l’affichage de la page sur laquelle le composant Google Maps est intégré. En règle générale, ce cookie n’est pas supprimé à la fermeture du navigateur, mais expire après un certain temps, à moins que l’utilisateur ne le supprime manuellement au préalable.      </p>
<p>Si l’utilisateur du site web n’est pas d’accord avec ce traitement des données, il a la possibilité de désactiver le service de Google Maps et d’empêcher ainsi la transmission de données à Google. Pour cela, il faut désactiver la fonction Javascript du navigateur, ce qui peut avoir pour conséquence que toutes les fonctions du site ne fonctionnent plus correctement.   </p>
<p>L’utilisation de Google Maps et des informations obtenues via Google Maps est soumise aux conditions d’utilisation de Google ainsi qu’aux conditions générales supplémentaires de Google Maps. De plus amples informations sur les conditions d’utilisation et la protection des données sont disponibles sur le site Internet de Google Maps.  </p>
<p><strong>13.5 Utilisation de plug-ins de médias sociaux</strong> <br>Le site Web de la Banque utilise des marque-pages sociaux ou des plug-ins de médias sociaux d’entreprises tierces (par ex. LinkedIn, etc.). Le traitement des données par des entreprises tierces est hors de portée de la Banque. En cliquant sur le plug-in, les entreprises tierces sont informées que la page correspondante du site Internet a été consultée. La Banque n’a aucune influence sur le traitement des données par les entreprises tierces. Si l’utilisation des plug-ins doit être empêchée, il est nécessaire de se désinscrire au préalable des comptes existants des entreprises tierces.      </p>
<p>Pour plus d’informations, par exemple sur le but et l’étendue de la collecte de données par les entreprises tierces, veuillez consulter directement le site web de ces entreprises.</p>
</div><h3 id="brxe-olszdd" class="brxe-heading daten-heading">14. réserve de modification</h3><div id="brxe-hizytz" class="brxe-text"><p>La Banque se réserve le droit d’adapter à tout moment la déclaration de confidentialité, dans le respect des dispositions légales relatives à la protection des données. La version actuelle de la présente déclaration de confidentialité peut être consultée sur le site Web de la Banque. </p>
</div><h3 id="brxe-qzzndw" class="brxe-heading daten-heading">15. coordonnées</h3><div id="brxe-tegoxs" class="brxe-text"><p>La Banque est considérée comme le responsable du traitement des données personnelles. Les questions relatives à la protection des données peuvent être adressées à :   </p>
<p>Hugocrest<br>Hugocrest Bank<br>Conseiller en protection des données<br>Rämistrasse 23 <br>8001 Zurich</p>
<p>Tél. 044 268 61 61   <br><a href="mailto:datenschutz@hugocrest.com">datenschutz@hugocrest.com  </a></p>
</div></div></section><div id="brxe-cd8595" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Bulletin d'information</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Soyez le premier à découvrir les dernières nouveautés et des conseils financiers utiles. Inscrivez-vous dès maintenant à notre newsletter et ne manquez plus aucune mise à jour importante. </p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="brxe-1a6463" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="fr_FR">
			
				<div class="form-group" role="group">
				<input id="form-field-42e948" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="Adresse électronique" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">S'inscrire</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      