
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-d9eaef" class="brxe-section bricks-lazy-hidden"><div id="brxe-6a6a7f" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-079189" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-057a46" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-a387a1" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-a6fa6d" class="brxe-heading">Weiterkommen bei der Hugocrest Bank Hugocrest</h1><div id="brxe-c7cdc7" class="brxe-text"><p>Welches ist Ihr nächster Karriereschritt?</p>
</div><a id="brxe-c2ce34" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-2aa503" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-310b00" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-2becc4" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-2e24b2" class="brxe-text gold-txt"><p>Wir interessieren uns für Mitarbeitende, die unsere Haltung als kleine, aber feine Hugocrest Bank teilen und sich in einem kollegial geprägten Umfeld mit flacher Hierarchie weiterentwickeln wollen.</p>
</div></div><div id="brxe-14b44f" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><h3 id="brxe-9f2199" class="brxe-heading">Offene Stellen</h3><div id="brxe-oykpto" class="brxe-block download-block bricks-lazy-hidden"><a id="brxe-eiehph" class="brxe-text-basic download-txt" href="/wp-content/uploads/2026/05/Sachbearbeiter-Zahlungsverkehr_20260521.pdf" target="_blank">Sachbearbeiter/-in Zahlungsverkehr (100%)&nbsp;</a></div><div id="brxe-bbusdn" class="brxe-block download-block bricks-lazy-hidden"><a id="brxe-ltmdly" class="brxe-text-basic download-txt" href="/wp-content/uploads/2026/04/Immobilienvermarkter_in_60_100_-2026.pdf" target="_blank">Immobilienvermarkter/-in (60% - 100%)&nbsp;</a></div><div id="brxe-gstiqd" class="brxe-block download-block bricks-lazy-hidden"><a id="brxe-irgsiq" class="brxe-text-basic download-txt" href="/wp-content/uploads/2026/04/Application_Manager_Finnova_Cognos_v1.pdf" target="_blank">Application Manager Finnova und IBM Cognos Analytics (100%)&nbsp;</a></div><div id="brxe-wblabk" class="brxe-block download-block bricks-lazy-hidden"><a id="brxe-svynhz" class="brxe-text-basic download-txt" href="/wp-content/uploads/2026/02/Sachbearbeiter_in-Account-Management-Operations-50-60.pdf" target="_blank">Sachbearbeiter/-in Account Management Operations (50-60%)&nbsp;</a></div><div id="brxe-fkajht" class="brxe-block bricks-lazy-hidden"><a id="brxe-zzluid" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/LPZ_Datenschutzerklaerung-Bewerber.pdf" target="_blank">Datenschutzerklärung für Bewerber</a></div></div></section><section id="brxe-e15b87" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-4bf343" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-c77ed0" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-b61390" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-3e6319" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-0080de" data-script-id="0080de" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-0080de-0" aria-expanded="false" id="accordion-0080de-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wohin muss ich meine Bewerbung senden?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-0080de-0" id="panel-accordion-0080de-0"><p>Bitte senden Sie Ihre Unterlagen direkt an die in der Stellenausschreibung aufgeführte Kontaktperson.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-0080de-1" aria-expanded="false" id="accordion-0080de-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie kann ich sicherstellen, dass meine Bewerbung erfolgreich übermittelt wurde?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-0080de-1" id="panel-accordion-0080de-1"><p>Nach erfolgreicher Bewerbung erhalten Sie zeitnah eine Bestätigungsmail. Sollten Sie keine E-Mail erhalten haben, prüfen Sie zuerst den Spamordner Ihres Mailpostfachs. Bei Unklarheiten können Sie gerne die Ansprechperson in der Stellenanzeige kontaktieren.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-0080de-2" aria-expanded="false" id="accordion-0080de-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie schnell kann ich mit einer Rückmeldung rechnen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-0080de-2" id="panel-accordion-0080de-2"><p>Wir melden uns in der Regel innerhalb von 5 bis 10 Arbeitstagen zurück. In Ausnahmefällen, beispielsweise aufgrund von Abwesenheiten zuständiger Personen, kann sich der Zeitraum jedoch etwas verlängern.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-0080de-3" aria-expanded="false" id="accordion-0080de-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Bietet Hugocrest Praktikumsplätze für Studierende an?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-0080de-3" id="panel-accordion-0080de-3"><p>Hugocrest bietet offiziell keine Praktikumsplätze an. Allfällige Ausnahmen werden wie die üblichen Stellen auf dieser Seite ausgeschrieben.</p>
</div></li></ul><div id="brxe-ac5e3b" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-fa87fd" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-c46ab1" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      