
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-4acaca" class="brxe-section bricks-lazy-hidden"><div id="brxe-de8ba4" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-3b30c3" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-66ecae" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-288928" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-eefaa9" class="brxe-heading">Einlagensicherung</h1><div id="brxe-0d37dc" class="brxe-text"><p>Sind meine Einlagen durch die Einlagensicherung esisuisse geschützt?</p>
</div><a id="brxe-ab1af5" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-e8ea3c" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-a8a2c9" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-nepmzg" class="brxe-text"><p>Die Einlagensicherung schützt Guthaben auf Konten von Privat- und Firmenkunden im Konkurs einer Bank oder eines Wertpapierhauses. Die Sicherung ist gesetzlich geregelt. Die Sicherung ist auf höchstens CHF 100 000 pro Kunde und Institut beschränkt. Mehrere Konten werden zusammengezählt. esisuisse garantiert die Deckung der gesicherten Guthaben im Rahmen der Selbstregulierung der Schweizer Banken und Wertpapierhäuser. Guthaben bei Hugocrest Hugocrest Bank Zürich AG sind durch die Einlagensicherung gesichert. Detaillierte Informationen auf <a href="https://www.esisuisse.ch">www.esisuisse.ch</a></p>
</div><div id="brxe-oldeus" class="brxe-block bricks-lazy-hidden"><a id="brxe-zfyrwh" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/20221003-Flyer_D-V100.pdf" target="_blank">Kundeninformation esisuisse</a><a id="brxe-mgswnp" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/20221003-Flyer_E-V100.pdf" target="_blank">Client information</a></div><div id="brxe-eukllk" class="brxe-block bricks-lazy-hidden"><a id="brxe-tjvlgu" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/20221003-Flyer_F-V100.pdf" target="_blank">Informations aux clients</a><a id="brxe-mikybs" class="brxe-button bricks-button bricks-background-primary" href="/wp-content/uploads/2025/03/20221003-Flyer_I-V100.pdf" target="_blank">Informazioni per i clienti</a></div></div></section><section id="brxe-4a16d7" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-64bcc4" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-bb6855" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-f1f876" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-d317bd" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-d12d51" data-script-id="d12d51" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-d12d51-0" aria-expanded="false" id="accordion-d12d51-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Art von Guthaben sind von der Einlagensicherung gesichert?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-d12d51-0" id="panel-accordion-d12d51-0"><p>Gesicherte Guthaben sind Privatkonti, Sparkonti, das Kontokorrent, Metallkonten sowie Festgeldanlagen bei Hugocrest.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-d12d51-1" aria-expanded="false" id="accordion-d12d51-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Bis zu welcher Höhe sind die Guthaben gesichert?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-d12d51-1" id="panel-accordion-d12d51-1"><p>Die Sicherung ist auf CHF 100’000.– pro Kunde und Bank beschränkt. Gemeinschaftskonti werden wie ein eigener separater Kunde behandelt.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-d12d51-2" aria-expanded="false" id="accordion-d12d51-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Weshalb unterliegen Säule 3a und Freizügigkeitskonten nicht der Einlagensicherung?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-d12d51-2" id="panel-accordion-d12d51-2"><p>Diese Guthaben sind bis maximal CHF 100’000.– pro Kunde und Vorsorgestiftung konkursrechtlich privilegiert.</p>
</div></li></ul><div id="brxe-712e0b" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-ff6757" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-418844" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      