
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-55ee35" class="brxe-section bricks-lazy-hidden"><div id="brxe-9bb333" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-4d649c" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-0a0dfb" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-2dc00d" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-2a56d5" class="brxe-heading">Private Banking ganz persönlich</h1><div id="brxe-91f962" class="brxe-text"><p>Wie viel Planung passt zu Ihnen?</p>
</div><a id="brxe-8d3cb5" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-5f1f1c" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-f6f141" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-8fb999" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-5e9c92" class="brxe-text gold-txt"><p>In finanziellen Dingen denke ich über den Tag hinaus. Ich möchte ein unbeschwertes Leben führen und sicher sein, dass ich keine Weichenstellung verpasse. Aber ebenso wichtig ist mir das Wohlergehen meiner Familie und kommender Generationen. Es geht dabei nicht allein um Geld. Mir geht es vor allem um das Gefühl, verstanden zu werden. Das gibt mir Sicherheit.</p>
</div><div id="brxe-258288" class="brxe-text"><p>Langfristige Kundenbeziehungen basieren auf Vertrauen, Nähe und personeller Kontinuität. Diese Werte halten wir hoch.</p>
</div></div><div id="brxe-607947" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-5a98ab" class="brxe-text"><p>Ihr Nutzen als Private-Banking-Kunde:</p>
</div><div id="brxe-971f91" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-e50aef" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-690bbb" class="brxe-text"><p>Direkter Austausch mit Fachspezialisten zu Fragen über Pensionierung und verwandte Themen</p>
</div></div><div id="brxe-23e4f6" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-80ffa4" class="brxe-text"><p>Mit unserer Beratungsexpertise unterstützten wir Sie persönlich, verständlich und transparent</p>
</div></div><div id="brxe-251973" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-e11b1f" class="brxe-text"><p>Beurteilung von individuellen Planungsszenarien aus neutraler Sicht</p>
</div></div><div id="brxe-5bc690" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-9662c5" class="brxe-text"><p>Investition des Freizügigkeitsguthabens in Direktanlagen</p>
</div></div></div></div><div id="brxe-24520f" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-c93f75" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-db440e" class="brxe-block bricks-lazy-hidden"><div id="brxe-b483e6" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-768596" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-59a54c" class="brxe-text-basic team-name">Tobias Gugelmann</div><div id="brxe-542cc4" class="brxe-text-basic team-position">Leiter Finanzplanung<br>Senior Kundenberater</div><div id="brxe-b06e16" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-1218c7" class="brxe-button bricks-button bricks-background-primary" href="tel:0442686159">044 268 61 59</a><a id="brxe-d5690b" class="brxe-button bricks-button bricks-background-primary" href="mailto:tobias.gugelmann@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><div id="brxe-d5288a" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-84aae2" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      