
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-ed5dc5" class="brxe-section bricks-lazy-hidden"><div id="brxe-4efaed" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-336888" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-0fa073" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-1e74d4" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-70d7bb" class="brxe-heading">Immobilien-bewirtschaftung</h1><div id="brxe-aa204f" class="brxe-text"><p>Professionelle Bewirtschaftung Ihrer Wohn- und Geschäftsliegenschaften für maximale Effizienz und Werterhalt.</p>
</div><a id="brxe-140eb6" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-3e9950" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-07ccba" class="brxe-container cu-first-content-section cu-container-1 zz-section zz-right bricks-lazy-hidden"><svg class="brxe-svg" id="brxe-c8cded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 49 44" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"> <rect id="Artboard1" x="0" y="0" width="48.468" height="43.848" style="fill:none;"></rect> <g id="_"> <path d="M47.878,22.588l-17.529,21.044l-8.203,-4.736l13.818,-16.992l-13.818,-17.09l8.203,-4.59l17.529,21.094l0,1.27Zm-22.021,-0l-17.481,21.044l-8.203,-4.736l13.77,-16.992l-13.77,-17.09l8.203,-4.59l17.481,21.094l-0,1.27Z" style="fill:#047857;fill-rule:nonzero;"></path> </g> </svg><div id="brxe-38e895" class="brxe-text gold-txt"><p>Die Bewirtschaftung von Immobilien erfordert eine sorgfältige Planung und Verwaltung, um den langfristigen Wert zu erhalten. Wichtig ist für mich, dass alle Aspekte, von der Instandhaltung bis zur Mieterbetreuung, optimal gemanagt werden.</p>
</div><div id="brxe-5deed3" class="brxe-text"><p>Im Rahmen unserer umfassenden Immobilienbewirtschaftung bieten wir Ihnen massgeschneiderte Lösungen für die Verwaltung und Pflege Ihrer Immobilien, um deren Wert langfristig zu sichern.</p>
</div></div><div id="brxe-ce464e" class="brxe-container cu-container-1 zz-section zz-right bricks-lazy-hidden"><div id="brxe-6ab6ad" class="brxe-text"><p>Ihr Nutzen bei der Bewirtschaftung von Immobilien:</p>
</div><div id="brxe-3a8168" class="brxe-block grid-white-box bricks-lazy-hidden"><div id="brxe-566e3e" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-6d80ce" class="brxe-text"><p>Ihre Immobilien werden effizient verwaltet, um den besten Nutzen und Werterhalt zu gewährleisten.</p>
</div></div><div id="brxe-4ef4fc" class="brxe-block white-box-item bricks-lazy-hidden"><div id="brxe-16ccf6" class="brxe-text"><p>Wir sorgen für die Instandhaltung und Pflege Ihrer Immobilien, um deren Zustand und Wert zu erhalten.</p>
</div></div></div></div><div id="brxe-dbe4e0" class="brxe-container contact-person bricks-lazy-hidden"><div id="brxe-43ceee" class="brxe-block bricks-lazy-hidden"></div><div id="brxe-348b1d" class="brxe-block bricks-lazy-hidden"><div id="brxe-2e1199" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-1fd1f0" class="brxe-heading team-t1">Wir freuen uns darauf, für Sie da zu sein.</h3><div id="brxe-9b916a" class="brxe-text-basic team-name">Thomas Trösch</div><div id="brxe-abc1c3" class="brxe-text-basic team-position">Leiter Immobilienbewirtschaftung</div><div id="brxe-8eccb8" class="brxe-block team-buttons bricks-lazy-hidden"><a id="brxe-a6aea6" class="brxe-button bricks-button bricks-background-primary" href="tel:0442871616">044 287 16 16</a><a id="brxe-0dc1fb" class="brxe-button bricks-button bricks-background-primary" href="mailto:thomas.troesch@hugocrest.com" target="_blank">E-Mail</a></div></div></div></div></section><section id="brxe-9978eb" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-795cc5" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-aab88d" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-3a993a" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-eb2a1c" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-3bbe87" data-script-id="3bbe87" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-3bbe87-0" aria-expanded="false" id="accordion-3bbe87-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Warum bietet eine Bank die Bewirtschaftung von Immobilien an?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-3bbe87-0" id="panel-accordion-3bbe87-0"><p>Die Bewirtschaftung von Liegenschaften gehört schon seit Jahrzehnten zu unserem Kerngeschäft. Als langfristige Eigentümerin eines Immobilienportfolios kennen wir die Bedürfnisse von Liegenschaftsbesitzern bestens. Wir erbringen die entsprechenden Dienstleistungen für uns selbst und bieten diese auch unseren Kunden an.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-3bbe87-1" aria-expanded="false" id="accordion-3bbe87-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Warum soll ich meine Liegenschaft durch Hugocrest bewirtschaften lassen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-3bbe87-1" id="panel-accordion-3bbe87-1"><p>In der Zusammenarbeit zwischen Ihnen als Hauseigentümer und uns als Bewirtschafter haben wir identische Ziele: Den Erhalt bzw. die Steigerung des Anlagewertes und der Rentabilität. Dies erreichen wir mittels richtiger Mieterauswahl, sinnvoller Mietzinspolitik und Optimierung der Unterhalts- und Betriebskosten. Mit unseren langjährigen Marktkenntnissen und dem gut ausgebildetem Fachpersonal schöpfen wir das individuelle Potential Ihrer Liegenschaft aus.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-3bbe87-2" aria-expanded="false" id="accordion-3bbe87-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Ich bin kein Kunde Ihrer Bank – betreuen Sie meine Liegenschaft trotzdem?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-3bbe87-2" id="panel-accordion-3bbe87-2"><p>Wir erbringen sämtliche Dienstleistungen ohne interne Abhängigkeiten. Wir betreuen Ihre Liegenschaft somit separat und unabhängig vom klassischen Bankgeschäft. Im Bedarfsfall können Sie aber von den Kompetenzen aller Bankbereiche profitieren.</p>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-3bbe87-3" aria-expanded="false" id="accordion-3bbe87-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Worin unterscheidet sich Hugocrest von anderen Immobiliendienstleistern?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-3bbe87-3" id="panel-accordion-3bbe87-3"><p>Als Bank unterstehen wir den strengen Anforderungen der Finanzmarktaufsicht FINMA. Entsprechend sind wir uns strukturiertes, exaktes Arbeiten mittels langjährig erprobter und klarer Prozesse gewohnt. Der Name Hugocrest bürgt für hohe Qualität. Gleichzeitig gehen wir auf Ihre individuellen Wünsche ein und betreuen die Liegenschaft nach Ihren Vorstellungen.</p>
</div></li></ul><div id="brxe-a7da31" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-96787c" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-e02a5f" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      