
export default function Page() {
  return (
    <main id="brx-content" dangerouslySetInnerHTML={{ __html: `<section id="brxe-cccc8e" class="brxe-section bricks-lazy-hidden"><div id="brxe-c339de" class="brxe-container cu-header-container bricks-lazy-hidden"><div id="brxe-2f569e" class="brxe-block cu-header-col-1 bricks-lazy-hidden"><div id="brxe-3138cc" class="brxe-block cu-header-txt-block bricks-lazy-hidden"><div id="brxe-0851e2" class="brxe-block bricks-lazy-hidden"><h1 id="brxe-8405c2" class="brxe-heading">Vorsorge für Privatkunden</h1><div id="brxe-27c3cd" class="brxe-text"><p>Planen Sie Ihre Zukunft mit unseren massgeschneiderten Vorsorgelösungen, die auf Ihre individuellen Bedürfnisse abgestimmt sind.</p>
</div><a id="brxe-600f64" class="brxe-button bricks-button bricks-background-primary" href="/kontakt/">Jetzt kontaktieren</a></div></div></div><div id="brxe-825a21" class="brxe-block cu-header-col-2 bricks-lazy-hidden"></div></div><div id="brxe-84dc9a" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-b09c5d" class="brxe-block side-padding img-col bricks-lazy-hidden"></div><div id="brxe-05bbd0" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-e41664" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-4464aa" class="brxe-heading">Flexible Freizügigkeitslösungen für Privatkunden</h3><div id="brxe-b2fb81" class="brxe-text"><p>Nutzen Sie unsere flexiblen Freizügigkeitslösungen, um Ihre Altersvorsorge optimal zu gestalten und von Steuervorteilen zu profitieren.</p>
</div><a id="brxe-f26c8f" class="brxe-button bricks-button bricks-background-primary" href="/freizugigkeitslosungen/">Mehr erfahren</a></div></div></div><div id="brxe-066656" class="brxe-container zz-section zz-right bricks-lazy-hidden"><div id="brxe-0e42de" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-61f336" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-c2ae82" class="brxe-heading">Flexible Säule-3a-Lösungen für Privatkunden</h3><div id="brxe-27e0c6" class="brxe-text"><p>Profitieren Sie von unseren flexiblen Lösungen für Ihre Säule-3a-Guthaben und maximieren Sie Ihre steuerlichen Vorteile.</p>
</div><a id="brxe-9a4d61" class="brxe-button bricks-button bricks-background-primary" href="/saule-3a/">Mehr erfahren</a></div></div><div id="brxe-178474" class="brxe-block img-col bricks-lazy-hidden"></div></div><div id="brxe-aac414" class="brxe-container cu-first-content-section zz-section zz-left bricks-lazy-hidden"><div id="brxe-7b30d6" class="brxe-block side-padding img-col bricks-lazy-hidden"></div><div id="brxe-ba7b80" class="brxe-block txt-col bricks-lazy-hidden"><div id="brxe-f33d03" class="brxe-block txt-col-block bricks-lazy-hidden"><h3 id="brxe-fda6e1" class="brxe-heading">Freies Sparen oder Anlegen 3b</h3><div id="brxe-55d0d7" class="brxe-text"><p>Gestalten Sie Ihre finanzielle Zukunft mit unseren freien Spar- und Anlagelösungen im Rahmen der Säule 3b.</p>
</div><a id="brxe-2d7511" class="brxe-button bricks-button bricks-background-primary" href="/freies-sparen-oder-anleger-3b/">Mehr erfahren</a></div></div></div></section><section id="brxe-d7ceb0" class="brxe-section faq-section bricks-lazy-hidden"><div id="brxe-75bc34" class="brxe-container cu-accordion-container bricks-lazy-hidden"><div id="brxe-080690" class="brxe-block side-padding faq-container bricks-lazy-hidden"><h3 id="brxe-dd51dd" class="brxe-heading">Häufig gestellte Fragen</h3><div id="brxe-d44f49" class="brxe-text"><p>Schnelle Antworten auf Ihre Fragen rund um unsere Bank und unsere Services. Alles, was Sie wissen müssen, leicht verständlich und direkt zugänglich.</p>
</div><ul id="brxe-e870ab" data-script-id="e870ab" class="brxe-accordion faq-accordion" role="presentation"><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-0" aria-expanded="false" id="accordion-e870ab-0" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was sind flexible Freizügigkeitslösungen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-0" id="panel-accordion-e870ab-0"><p>Flexible Freizügigkeitslösungen ermöglichen es Ihnen, Ihre Vorsorgegelder nach einem Jobwechsel, einer Pensionierung oder einer Pause im Berufsleben sicher und individuell zu verwalten.</p>
<p>Unsere Lösungen bieten:</p>
<ul>
<li>Vielfältige Anlagemöglichkeiten: Ihr Kapital kann sicher oder renditeorientiert angelegt werden.</li>
<li>Flexibilität: Zugriff auf Ihr Vorsorgekapital bei wichtigen Lebensereignissen wie Erwerb von Wohneigentum oder Auswanderung.</li>
<li>Transparenz: Transparente und faire Kostenstrukturen.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-1" aria-expanded="false" id="accordion-e870ab-1" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was passiert mit meinen Vorsorgegeldern bei einem Jobwechsel?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-1" id="panel-accordion-e870ab-1"><p>Wenn Sie Ihren Job wechseln oder kündigen, wird Ihr Vorsorgekapital auf ein Freizügigkeitskonto übertragen.</p>
<p>Unsere Lösungen gewährleisten:</p>
<ul>
<li>Sicherheit: Ihr Kapital bleibt geschützt.</li>
<li>Flexibilität: Möglichkeit zur Anlage in renditestarke Fonds oder Sparkonten.</li>
<li>Steuerliche Vorteile: Optimierte Verwaltung Ihres Vorsorgekapitals.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-2" aria-expanded="false" id="accordion-e870ab-2" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was ist die Säule 3a und warum sollte ich diese nutzen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-2" id="panel-accordion-e870ab-2"><p>Die Säule 3a ist ein freiwilliges Vorsorgeinstrument in der Schweiz, das Ihnen erlaubt, steuerbegünstigt für Ihre Zukunft zu sparen oder anzulegen.</p>
<p>Ihre Vorteile:</p>
<ul>
<li>Steuerersparnis: Beiträge können von Ihrem steuerbaren Einkommen abgezogen werden.</li>
<li>Renditechancen: Möglichkeit, Ihr Kapital in Fonds oder andere Wertschriften zu investieren.</li>
<li>Flexibilität: Anpassbare Lösungen, die auf Ihre persönlichen Ziele abgestimmt sind.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-3" aria-expanded="false" id="accordion-e870ab-3" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Wie flexibel sind die Säule 3a-Lösungen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-3" id="panel-accordion-e870ab-3"><p>Unsere Säule 3a-Lösungen passen sich Ihren Bedürfnissen an:</p>
<ul>
<li>Anlageoptionen: Von konservativen Strategien bis hin zu dynamischen Investments.</li>
<li>Individuelle Beiträge: Sie entscheiden, wann und wie viel Sie einzahlen möchten (bis zum jährlichen Maximalbetrag).</li>
<li>Auszahlungen: Bei Pensionierung, Erwerb von Wohneigentum, Selbstständigkeit oder Auswanderung.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-4" aria-expanded="false" id="accordion-e870ab-4" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Was bedeutet freies Sparen oder Anlegen 3b?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-4" id="panel-accordion-e870ab-4"><p>Freies Sparen oder Anlegen bietet Ihnen maximale Flexibilität bei der Verwaltung Ihrer finanziellen Mittel:</p>
<ul>
<li>Kostengünstige Anlageoptionen: Von monatlichen Sparbeiträgen bis zu Entnahmepläne flexibel in beispielsweise kostengünstige ETFs investieren.</li>
<li>Flexibilität: Im Gegensatz zur Säule 3a können Sie jederzeit mit Einhaltung der Fristen über Ihr Geld verfügen.</li>
<li>Unabhängigkeit: Ideal für kurz- und mittelfristige Sparziele oder für die Ergänzung Ihrer Vorsorge.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-5" aria-expanded="false" id="accordion-e870ab-5" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Vorteile bieten die Lösungen für Privatkunden?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-5" id="panel-accordion-e870ab-5"><p>Unsere Lösungen bieten:</p>
<ul>
<li>Flexibilität: Anpassung an Ihre persönlichen Lebensziele und Bedürfnisse.</li>
<li>Sicherheit: Transparente und verlässliche Verwaltung Ihres Kapitals.</li>
<li>Renditeorientierung: Breite Auswahl an Anlageprodukten für Wachstum und Sicherheit.</li>
</ul>
</div></li><li class="accordion-item"><div class="accordion-title-wrapper" aria-controls="panel-accordion-e870ab-6" aria-expanded="false" id="accordion-e870ab-6" role="button" tabindex="0"><div class="accordion-title"><h5 class="title">Welche Kosten können hierbei entstehen?</h5><svg class="icon expanded" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg><svg class="icon" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" width="100%" height="100%" viewBox="0 0 40 40" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;"> <g id="Gruppe_1159"> <circle id="Ellipse_78" cx="20" cy="20" r="20" style="fill:#047857;"></circle> <path id="Linie_231" d="M10,20l20,0" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> <path id="Linie_232" d="M20,10l0,20" style="fill:none;fill-rule:nonzero;stroke:#fff;stroke-width:2px;"></path> </g> </svg></div></div><div class="accordion-content-wrapper" role="region" aria-labelledby="accordion-e870ab-6" id="panel-accordion-e870ab-6"><p>Die anfallenden Kosten können je nach Produkt und Leistung variieren. Sie haben jederzeit die Möglichkeit, einen vollständigen Einblick in die anfallenden Gebühren zu erhalten. Ihr persönlicher Berater steht Ihnen gerne zur Verfügung. Zusätzlich finden Sie weitere Informationen in Ihren Produktunterlagen.</p>
</div></li></ul><div id="brxe-46666c" class="brxe-divider horizontal"><div class="line"></div></div></div></div></section><div id="brxe-244f69" class="brxe-template"><section id="brxe-409fcc" class="brxe-section bricks-lazy-hidden"><div id="brxe-e1548e" class="brxe-container bricks-lazy-hidden"><div id="brxe-887bad" class="brxe-block side-padding bricks-lazy-hidden"><div id="brxe-52b1d0" class="brxe-block bricks-lazy-hidden"><div id="brxe-fa1e1e" class="brxe-block bricks-lazy-hidden"><h3 id="brxe-132b1d" class="brxe-heading">Newsletter</h3><div id="brxe-1c4dd2" class="brxe-text"><p>Erfahren Sie als Erster von den neuesten Entwicklungen und nützlichen Finanztipps. Melden Sie sich jetzt für unseren Newsletter an und verpassen Sie keine wichtigen Updates mehr.</p>
</div></div></div><div id="brxe-ffc162" class="brxe-block bricks-lazy-hidden">		<form id="formEmail" data-script-id="1a6463" class="brxe-form" method="post" data-element-id="1a6463" data-lang="de_DE">
			
				<div class="form-group" role="group">
				<input id="form-field-45e110" name="form-field-ef0813" aria-label="Email" type="email" value="" placeholder="E-Mail-Adresse" maxlength="320" required="">
				
				
							</div>
				
			<div class="form-group submit-button-wrapper">
				<button type="submit" class="bricks-button bricks-background-primary">
					<span class="text">Anmelden</span><span class="loading"><svg version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g stroke-linecap="round" stroke-width="1" stroke="currentColor" fill="none" stroke-linejoin="round"><path d="M0.927,10.199l2.787,4.151l3.205,-3.838"></path><path d="M23.5,14.5l-2.786,-4.15l-3.206,3.838"></path><path d="M20.677,10.387c0.834,4.408 -2.273,8.729 -6.509,9.729c-2.954,0.699 -5.916,-0.238 -7.931,-2.224"></path><path d="M3.719,14.325c-1.314,-4.883 1.969,-9.675 6.538,-10.753c3.156,-0.747 6.316,0.372 8.324,2.641"></path></g><path fill="none" d="M0,0h24v24h-24Z"></path></svg>
</span>				</button>
			</div>
		</form>
		</div></div></div></section></div>` }} />
  );
}
      